export const moduleDependencies: Record<string, string[]> = {
  sales: ['inventory', 'third_parties'],
  purchases: ['inventory', 'third_parties'],
  quotes: ['sales'],
  purchase_orders: ['purchases'],
  expenses: ['third_parties'],
  ar_ap: ['third_parties'],
  accounting: ['ar_ap'],
  banking: ['accounting'],
  fixed_assets: ['accounting'],
  cost_centers: ['accounting'],
  tax: ['accounting'],
  closing: ['accounting'],
  exogenous: ['accounting', 'tax'],
  reports: ['accounting'],
  point_of_sale: ['sales', 'inventory'],
  cash_registers: ['point_of_sale'],
  time_attendance: ['core_hr'],
  leaves_vacations: ['core_hr'],
  hr_payroll: ['core_hr'],
  hr_expenses: ['core_hr'],
  hr_performance: ['core_hr'],
  inventory_management: ['inventory'],
  electronic_documents: ['sales'],
};
