import { ActionDef } from '../types';

// ===== MÓDULO 30: CRM (82 permisos) =====
export const crmActions: ActionDef[] = [
    { action_key: 'crm.view', action_name: 'Acceder al CRM', description: 'Acceder al CRM' },
    { action_key: 'crm.dashboard.view', action_name: 'Ver Dashboard CRM', description: 'Ver dashboard CRM' },
    { action_key: 'crm.leads.view', action_name: 'Ver Leads', description: 'Ver leads' },
    { action_key: 'crm.leads.create', action_name: 'Crear Lead', description: 'Crear lead' },
    { action_key: 'crm.leads.edit', action_name: 'Editar Lead', description: 'Editar lead' },
    { action_key: 'crm.leads.delete', action_name: 'Eliminar Lead', description: 'Eliminar lead' },
    { action_key: 'crm.leads.assign', action_name: 'Asignar Lead', description: 'Asignar lead' },
    { action_key: 'crm.leads.bulk_assign', action_name: 'Asignación Masiva', description: 'Asignación masiva leads' },
    { action_key: 'crm.leads.import', action_name: 'Importar Leads', description: 'Importar leads' },
    { action_key: 'crm.leads.export', action_name: 'Exportar Leads', description: 'Exportar leads' },
    { action_key: 'crm.leads.convert', action_name: 'Convertir Lead', description: 'Convertir lead' },
    { action_key: 'crm.leads.timeline.view', action_name: 'Ver Timeline', description: 'Ver timeline lead' },
    { action_key: 'crm.contacts.view', action_name: 'Ver Contactos', description: 'Ver contactos' },
    { action_key: 'crm.contacts.create', action_name: 'Crear Contacto', description: 'Crear contacto' },
    { action_key: 'crm.contacts.edit', action_name: 'Editar Contacto', description: 'Editar contacto' },
    { action_key: 'crm.contacts.delete', action_name: 'Eliminar Contacto', description: 'Eliminar contacto' },
    { action_key: 'crm.contacts.segment', action_name: 'Segmentar Contacto', description: 'Segmentar contacto' },
    { action_key: 'crm.contacts.whatsapp_chat', action_name: 'Abrir Chat WhatsApp', description: 'Abrir chat WhatsApp' },
    { action_key: 'crm.contacts.send_template', action_name: 'Enviar Plantilla', description: 'Enviar plantilla' },
    { action_key: 'crm.segmentation.configure', action_name: 'Configurar Segmentación', description: 'Configurar segmentación' },
    { action_key: 'crm.opportunities.view', action_name: 'Ver Oportunidades', description: 'Ver oportunidades' },
    { action_key: 'crm.opportunities.create', action_name: 'Crear Oportunidad', description: 'Crear oportunidad' },
    { action_key: 'crm.opportunities.edit', action_name: 'Editar Oportunidad', description: 'Editar oportunidad' },
    { action_key: 'crm.opportunities.delete', action_name: 'Eliminar Oportunidad', description: 'Eliminar oportunidad' },
    { action_key: 'crm.opportunities.change_stage', action_name: 'Cambiar Etapa', description: 'Cambiar etapa oportunidad' },
    { action_key: 'crm.opportunities.bulk_change_stage', action_name: 'Cambio Masivo Etapa', description: 'Cambio masivo etapa' },
    { action_key: 'crm.opportunities.mark_lost', action_name: 'Marcar Perdida', description: 'Marcar como perdida' },
    { action_key: 'crm.opportunities.create_quote', action_name: 'Crear Cotización', description: 'Crear cotización desde oportunidad' },
    { action_key: 'crm.opportunities.view_quotes', action_name: 'Ver Cotizaciones', description: 'Ver cotizaciones oportunidad' },
    { action_key: 'crm.activities.view', action_name: 'Ver Actividades', description: 'Ver actividades' },
    { action_key: 'crm.activities.create', action_name: 'Crear Actividad', description: 'Crear actividad' },
    { action_key: 'crm.activities.edit', action_name: 'Editar Actividad', description: 'Editar actividad' },
    { action_key: 'crm.activities.delete', action_name: 'Eliminar Actividad', description: 'Eliminar actividad' },
    { action_key: 'crm.activities.complete', action_name: 'Completar Actividad', description: 'Completar actividad' },
    { action_key: 'crm.activities.cancel', action_name: 'Cancelar Actividad', description: 'Cancelar actividad' },
    { action_key: 'crm.campaigns.view', action_name: 'Ver Campañas', description: 'Ver campañas' },
    { action_key: 'crm.campaigns.create', action_name: 'Crear Campaña', description: 'Crear campaña' },
    { action_key: 'crm.campaigns.edit', action_name: 'Editar Campaña', description: 'Editar campaña' },
    { action_key: 'crm.campaigns.delete', action_name: 'Eliminar Campaña', description: 'Eliminar campaña' },
    { action_key: 'crm.campaigns.configure_hours', action_name: 'Configurar Horarios', description: 'Configurar horarios campaña' },
    { action_key: 'crm.campaigns.view_report', action_name: 'Ver Reporte Campaña', description: 'Ver reporte campaña' },
    { action_key: 'crm.forms.view', action_name: 'Ver Formularios', description: 'Ver formularios' },
    { action_key: 'crm.forms.create', action_name: 'Crear Formulario', description: 'Crear formulario' },
    { action_key: 'crm.forms.edit', action_name: 'Editar Formulario', description: 'Editar formulario' },
    { action_key: 'crm.forms.delete', action_name: 'Eliminar Formulario', description: 'Eliminar formulario' },
    { action_key: 'crm.forms.toggle', action_name: 'Activar/Desactivar', description: 'Activar/desactivar formulario' },
    { action_key: 'crm.forms.view_submissions', action_name: 'Ver Envíos', description: 'Ver envíos formulario' },
    { action_key: 'crm.forms.embed', action_name: 'Obtener Código Embed', description: 'Obtener código embed' },
    { action_key: 'crm.automations.view', action_name: 'Ver Automatizaciones', description: 'Ver automatizaciones' },
    { action_key: 'crm.automations.create', action_name: 'Crear Automatización', description: 'Crear automatización' },
    { action_key: 'crm.automations.edit', action_name: 'Editar Automatización', description: 'Editar automatización' },
    { action_key: 'crm.automations.delete', action_name: 'Eliminar Automatización', description: 'Eliminar automatización' },
    { action_key: 'crm.automations.toggle', action_name: 'Activar/Desactivar', description: 'Activar/desactivar automatización' },
    { action_key: 'crm.automations.test', action_name: 'Probar Automatización', description: 'Probar automatización' },
    { action_key: 'crm.whatsapp.view', action_name: 'Ver WhatsApp', description: 'Ver WhatsApp' },
    { action_key: 'crm.whatsapp.send_message', action_name: 'Enviar Mensaje', description: 'Enviar mensaje WhatsApp' },
    { action_key: 'crm.whatsapp.send_template', action_name: 'Enviar Plantilla', description: 'Enviar plantilla WhatsApp' },
    { action_key: 'crm.whatsapp.manage_conversations', action_name: 'Gestionar Conversaciones WA', description: 'Asignar, cerrar y reabrir conversaciones WhatsApp' },
    { action_key: 'crm.whatsapp.sync_templates', action_name: 'Sincronizar Plantillas WA', description: 'Sincronizar plantillas desde Twilio Content API' },
    { action_key: 'crm.whatsapp_templates.view', action_name: 'Ver Plantillas WA', description: 'Ver plantillas WhatsApp' },
    { action_key: 'crm.whatsapp_templates.create', action_name: 'Crear Plantilla WA', description: 'Crear plantilla WhatsApp' },
    { action_key: 'crm.whatsapp_templates.edit', action_name: 'Editar Plantilla WA', description: 'Editar plantilla WhatsApp' },
    { action_key: 'crm.whatsapp_templates.delete', action_name: 'Eliminar Plantilla WA', description: 'Eliminar plantilla WhatsApp' },
    { action_key: 'crm.whatsapp_templates.preview', action_name: 'Previsualizar Plantilla', description: 'Previsualizar plantilla' },
    { action_key: 'crm.whatsapp_templates.submit_approval', action_name: 'Enviar a Aprobación', description: 'Enviar plantilla a aprobación' },
    { action_key: 'crm.email_marketing.view', action_name: 'Ver Email Marketing', description: 'Ver email marketing' },
    { action_key: 'crm.email_marketing.create', action_name: 'Crear Campaña Email', description: 'Crear campaña email' },
    { action_key: 'crm.email_marketing.edit', action_name: 'Editar Campaña Email', description: 'Editar campaña email' },
    { action_key: 'crm.email_marketing.delete', action_name: 'Eliminar Campaña Email', description: 'Eliminar campaña email' },
    { action_key: 'crm.email_marketing.send', action_name: 'Enviar Campaña', description: 'Enviar campaña email' },
    { action_key: 'crm.email_marketing.view_stats', action_name: 'Ver Estadísticas', description: 'Ver estadísticas email' },
    { action_key: 'crm.team.view', action_name: 'Ver Equipo', description: 'Ver equipo CRM' },
    { action_key: 'crm.team.manage', action_name: 'Gestionar Equipo', description: 'Gestionar equipo CRM' },
    { action_key: 'crm.settings.stages.view', action_name: 'Ver Etapas', description: 'Ver etapas del pipeline' },
    { action_key: 'crm.settings.stages.manage', action_name: 'Gestionar Etapas', description: 'Crear, editar, reordenar y eliminar etapas pipeline' },
    { action_key: 'crm.tags.view', action_name: 'Ver Tags', description: 'Ver tags de contactos' },
    { action_key: 'crm.tags.create', action_name: 'Crear Tag', description: 'Crear tag de contacto' },
    { action_key: 'crm.tags.edit', action_name: 'Editar Tag', description: 'Editar tag de contacto' },
    { action_key: 'crm.tags.delete', action_name: 'Eliminar Tag', description: 'Eliminar tag de contacto' },
    { action_key: 'crm.integrations.view', action_name: 'Ver Integraciones', description: 'Ver configuración de integraciones (SMTP, Twilio)' },
    { action_key: 'crm.integrations.manage', action_name: 'Gestionar Integraciones', description: 'Configurar y probar integraciones (SMTP, Twilio)' },
    { action_key: 'crm.reports.view', action_name: 'Ver Reportes CRM', description: 'Ver reportes CRM' },
    { action_key: 'crm.reports.performance', action_name: 'Ver Rendimiento', description: 'Ver rendimiento equipo' },
  ];
