import { ActionDef } from '../types';

// ===== MÓDULO 27: HR_PAYROLL - Nómina (38 permisos) =====
export const hr_payrollActions: ActionDef[] = [
    { action_key: 'payroll.view', action_name: 'Ver Nómina', description: 'Ver nómina' },
    { action_key: 'payroll.configure', action_name: 'Configurar Nómina', description: 'Configurar nómina' },
    { action_key: 'payroll_settlements.view', action_name: 'Ver Liquidaciones', description: 'Ver liquidaciones' },
    { action_key: 'payroll_settlements.create', action_name: 'Crear Liquidación', description: 'Crear liquidación' },
    { action_key: 'payroll_settlements.edit', action_name: 'Editar Liquidación', description: 'Editar liquidación' },
    { action_key: 'payroll_settlements.delete', action_name: 'Eliminar Liquidación', description: 'Eliminar liquidación' },
    { action_key: 'payroll_settlements.calculate', action_name: 'Calcular Liquidación', description: 'Calcular liquidación' },
    { action_key: 'payroll_settlements.approve', action_name: 'Aprobar Liquidación', description: 'Aprobar liquidación' },
    { action_key: 'payroll_settlements.contabilize', action_name: 'Contabilizar Liquidación', description: 'Contabilizar liquidación' },
    { action_key: 'payroll_settlements.void', action_name: 'Anular Liquidación', description: 'Anular liquidación' },
    { action_key: 'payroll_novelties.view', action_name: 'Ver Novedades', description: 'Ver novedades' },
    { action_key: 'payroll_novelties.create', action_name: 'Crear Novedad', description: 'Crear novedad' },
    { action_key: 'payroll_novelties.edit', action_name: 'Editar Novedad', description: 'Editar novedad' },
    { action_key: 'payroll_novelties.delete', action_name: 'Eliminar Novedad', description: 'Eliminar novedad' },
    { action_key: 'payroll_novelties.approve', action_name: 'Aprobar Novedades', description: 'Aprobar novedades' },
    { action_key: 'payroll_concepts.view', action_name: 'Ver Conceptos', description: 'Ver conceptos' },
    { action_key: 'payroll_concepts.create', action_name: 'Crear Concepto', description: 'Crear concepto' },
    { action_key: 'payroll_concepts.edit', action_name: 'Editar Concepto', description: 'Editar concepto' },
    { action_key: 'payroll_concepts.delete', action_name: 'Eliminar Concepto', description: 'Eliminar concepto' },
    { action_key: 'payroll_concepts.initialize', action_name: 'Inicializar Conceptos DIAN', description: 'Inicializar conceptos DIAN' },
    { action_key: 'payroll_uvt.view', action_name: 'Ver Tabla UVT', description: 'Ver tramos UVT retención en la fuente' },
    { action_key: 'payroll_uvt.create', action_name: 'Crear Tramo UVT', description: 'Crear tramo UVT' },
    { action_key: 'payroll_uvt.edit', action_name: 'Editar Tramo UVT', description: 'Editar tramo UVT' },
    { action_key: 'payroll_uvt.delete', action_name: 'Eliminar Tramo UVT', description: 'Eliminar tramo UVT' },
    { action_key: 'payroll_uvt.replicate', action_name: 'Replicar Tabla UVT', description: 'Replicar tramos UVT de un año a otro' },
    { action_key: 'payslips.view', action_name: 'Ver Desprendibles', description: 'Ver desprendibles' },
    { action_key: 'payslips.download', action_name: 'Descargar Desprendible', description: 'Descargar desprendible' },
    { action_key: 'payslips.send_email', action_name: 'Enviar por Email', description: 'Enviar desprendible por email' },
    { action_key: 'payslips.bulk_send', action_name: 'Envío Masivo', description: 'Envío masivo desprendibles' },
    { action_key: 'payroll_dian.send', action_name: 'Enviar Nómina DIAN', description: 'Enviar nómina DIAN' },
    { action_key: 'payroll_dian.view', action_name: 'Ver Estado DIAN', description: 'Ver estado DIAN' },
    { action_key: 'pila.generate', action_name: 'Generar PILA', description: 'Generar PILA' },
    { action_key: 'pila.download', action_name: 'Descargar PILA', description: 'Descargar PILA' },
    { action_key: 'pila.send', action_name: 'Enviar PILA', description: 'Enviar PILA' },
    { action_key: 'pila.history.view', action_name: 'Ver Historial PILA', description: 'Ver historial PILA' },
    { action_key: 'severance.view', action_name: 'Ver Liquidaciones Definitivas', description: 'Ver liquidaciones definitivas' },
    { action_key: 'severance.create', action_name: 'Crear Liquidación Definitiva', description: 'Crear liquidación definitiva' },
    { action_key: 'severance.approve', action_name: 'Aprobar Liquidación Definitiva', description: 'Aprobar liquidación definitiva' },
  ];
