import { ActionDef } from '../types';

// ===== MÓDULO 9: INVENTORY - Inventario (36 permisos) =====
export const inventoryActions: ActionDef[] = [
    { action_key: 'inventory.items.view', action_name: 'Ver Productos', description: 'Ver catálogo de productos' },
    { action_key: 'inventory.items.create', action_name: 'Crear Producto', description: 'Crear nuevo producto' },
    { action_key: 'inventory.items.edit', action_name: 'Editar Producto', description: 'Editar producto' },
    { action_key: 'inventory.items.delete', action_name: 'Eliminar Producto', description: 'Eliminar producto' },
    { action_key: 'inventory.items.import', action_name: 'Importar Productos', description: 'Importar desde Excel' },
    { action_key: 'inventory.items.export', action_name: 'Exportar Productos', description: 'Exportar a Excel' },
    { action_key: 'inventory.items.upload_image', action_name: 'Subir Imagen', description: 'Subir imagen de producto' },
    { action_key: 'inventory.items.view_detail', action_name: 'Ver Detalle Producto', description: 'Ver detalle de producto' },
    { action_key: 'inventory.categories.view', action_name: 'Ver Categorías', description: 'Ver categorías' },
    { action_key: 'inventory.categories.create', action_name: 'Crear Categoría', description: 'Crear categoría' },
    { action_key: 'inventory.categories.edit', action_name: 'Editar Categoría', description: 'Editar categoría' },
    { action_key: 'inventory.categories.delete', action_name: 'Eliminar Categoría', description: 'Eliminar categoría' },
    { action_key: 'inventory.stock.view', action_name: 'Ver Stock', description: 'Ver niveles de stock' },
    { action_key: 'inventory.kardex.view', action_name: 'Ver Kardex', description: 'Ver kardex de movimientos de inventario' },
    { action_key: 'inventory.adjustments.create', action_name: 'Ajustar Inventario', description: 'Crear ajuste manual de inventario' },
    { action_key: 'inventory.product_transfers.view', action_name: 'Ver Transferencias de Producto', description: 'Ver transferencias entre productos (padre/combinaciones)' },
    { action_key: 'inventory.product_transfers.create', action_name: 'Solicitar Transferencia de Producto', description: 'Solicitar transferencia de stock entre productos' },
    { action_key: 'inventory.product_transfers.approve_reject', action_name: 'Aprobar/Rechazar Transferencia de Producto', description: 'Aprobar o rechazar transferencias entre productos' },
    { action_key: 'inventory.storage_transfers.view', action_name: 'Ver Transferencias entre Bodegas', description: 'Ver transferencias de stock entre bodegas' },
    { action_key: 'inventory.storage_transfers.create', action_name: 'Solicitar Transferencia entre Bodegas', description: 'Solicitar transferencia de stock entre bodegas' },
    { action_key: 'inventory.storage_transfers.approve_reject', action_name: 'Aprobar/Rechazar Transferencia entre Bodegas', description: 'Aprobar o rechazar transferencias entre bodegas' },
    { action_key: 'inventory.attributes.view', action_name: 'Ver Atributos', description: 'Ver atributos' },
    { action_key: 'inventory.attributes.create', action_name: 'Crear Atributo', description: 'Crear atributo' },
    { action_key: 'inventory.attributes.edit', action_name: 'Editar Atributo', description: 'Editar atributo' },
    { action_key: 'inventory.attributes.delete', action_name: 'Eliminar Atributo', description: 'Eliminar atributo' },
    { action_key: 'inventory.attributes.import', action_name: 'Importar Atributos', description: 'Importar atributos' },
    { action_key: 'inventory.attribute_options.view', action_name: 'Ver Opciones de Atributo', description: 'Ver opciones de atributo' },
    { action_key: 'inventory.attribute_options.create', action_name: 'Crear Opción de Atributo', description: 'Crear opción de atributo' },
    { action_key: 'inventory.attribute_options.edit', action_name: 'Editar Opción de Atributo', description: 'Editar opción de atributo' },
    { action_key: 'inventory.attribute_options.delete', action_name: 'Eliminar Opción de Atributo', description: 'Eliminar opción de atributo' },
    { action_key: 'inventory.attribute_options.import', action_name: 'Importar Opciones de Atributo', description: 'Importar opciones de atributo' },
    { action_key: 'inventory.combinations.manage_attributes', action_name: 'Gestionar Atributos de Producto', description: 'Asignar/quitar atributos a un producto para combinaciones' },
    { action_key: 'inventory.combinations.view', action_name: 'Ver Combinaciones', description: 'Ver combinaciones de producto' },
    { action_key: 'inventory.combinations.create', action_name: 'Crear Combinación', description: 'Crear combinación de producto' },
    { action_key: 'inventory.combinations.edit', action_name: 'Editar Combinación', description: 'Editar combinación de producto' },
    { action_key: 'inventory.combinations.delete', action_name: 'Eliminar Combinación', description: 'Eliminar combinación de producto' },
  ];
