import { ActionDef } from '../types';

// ===== MÓDULO 5: SALES - Ventas/Facturación (28 permisos) =====
export const salesActions: ActionDef[] = [
    { action_key: 'sales.invoices.view', action_name: 'Ver Facturas', description: 'Ver listado de facturas' },
    { action_key: 'sales.invoices.create', action_name: 'Crear Factura', description: 'Crear nuevas facturas de venta' },
    { action_key: 'sales.invoices.edit', action_name: 'Editar Factura', description: 'Editar factura borrador' },
    { action_key: 'sales.invoices.delete', action_name: 'Eliminar Factura', description: 'Eliminar factura borrador' },
    { action_key: 'sales.invoices.email', action_name: 'Enviar por Email', description: 'Enviar factura al cliente' },
    { action_key: 'sales.invoices.print', action_name: 'Imprimir Factura', description: 'Imprimir factura' },
    { action_key: 'sales.invoices.export', action_name: 'Exportar Facturas', description: 'Exportar facturas a Excel/PDF' },
    { action_key: 'sales.invoices.import', action_name: 'Importar Facturas', description: 'Importar facturas desde archivo' },
    { action_key: 'sales.invoices.view_detail', action_name: 'Ver Detalle Factura', description: 'Ver detalle de factura' },
    { action_key: 'sales.credit_notes.view', action_name: 'Ver Notas Crédito', description: 'Ver notas crédito' },
    { action_key: 'sales.credit_notes.view_detail', action_name: 'Ver Detalle NC', description: 'Ver detalle de nota crédito' },
    { action_key: 'sales.credit_notes.create', action_name: 'Crear Nota Crédito', description: 'Crear nota crédito' },
    { action_key: 'sales.credit_notes.email', action_name: 'Enviar NC por Email', description: 'Enviar nota crédito al cliente' },
    { action_key: 'sales.credit_notes.print', action_name: 'Imprimir NC', description: 'Imprimir nota crédito' },
    { action_key: 'sales.credit_notes.export', action_name: 'Exportar NC', description: 'Exportar notas crédito a Excel/PDF' },
    { action_key: 'sales.credit_notes.import', action_name: 'Importar NC', description: 'Importar notas crédito desde archivo' },
    { action_key: 'sales.debit_notes.view', action_name: 'Ver Notas Débito', description: 'Ver notas débito' },
    { action_key: 'sales.debit_notes.view_detail', action_name: 'Ver Detalle ND', description: 'Ver detalle de nota débito' },
    { action_key: 'sales.debit_notes.create', action_name: 'Crear Nota Débito', description: 'Crear nota débito' },
    { action_key: 'sales.debit_notes.email', action_name: 'Enviar ND por Email', description: 'Enviar nota débito al cliente' },
    { action_key: 'sales.debit_notes.print', action_name: 'Imprimir ND', description: 'Imprimir nota débito' },
    { action_key: 'sales.debit_notes.export', action_name: 'Exportar ND', description: 'Exportar notas débito a Excel/PDF' },
    { action_key: 'sales.debit_notes.import', action_name: 'Importar ND', description: 'Importar notas débito desde archivo' },
    { action_key: 'sales.recurrent.view', action_name: 'Ver Plantillas Recurrentes', description: 'Ver plantillas de facturas recurrentes' },
    { action_key: 'sales.recurrent.create', action_name: 'Crear Plantilla Recurrente', description: 'Crear plantilla recurrente' },
    { action_key: 'sales.recurrent.edit', action_name: 'Editar Plantilla Recurrente', description: 'Editar plantilla recurrente' },
    { action_key: 'sales.recurrent.delete', action_name: 'Eliminar Plantilla', description: 'Eliminar plantilla recurrente' },
    { action_key: 'sales.recurrent.execute', action_name: 'Ejecutar Plantilla', description: 'Ejecutar plantilla manualmente' },
    { action_key: 'sales.recurrent.toggle', action_name: 'Activar/Desactivar Plantilla', description: 'Activar o desactivar plantilla' },
  ];
