/**
 * Países - Datos DIAN
 * IDs específicos del sistema anterior
 */
export const countries = [
  { id: '1', name: 'Afganistán', code: 'AF' },
  { id: '2', name: 'Åland', code: 'AX' },
  { id: '3', name: 'Albania', code: 'AL' },
  { id: '4', name: 'Alemania', code: 'DE' },
  { id: '5', name: 'Andorra', code: 'AD' },
  { id: '6', name: 'Angola', code: 'AO' },
  { id: '7', name: 'Anguila', code: 'AI' },
  { id: '8', name: 'Antártida', code: 'AQ' },
  { id: '9', name: 'Antigua y Barbuda', code: 'AG' },
  { id: '10', name: 'Arabia Saudita', code: 'SA' },
  { id: '11', name: 'Argelia', code: 'DZ' },
  { id: '12', name: 'Argentina', code: 'AR' },
  { id: '13', name: 'Armenia', code: 'AM' },
  { id: '14', name: 'Aruba', code: 'AW' },
  { id: '15', name: 'Australia', code: 'AU' },
  { id: '16', name: 'Austria', code: 'AT' },
  { id: '17', name: 'Azerbaiyán', code: 'AZ' },
  { id: '18', name: 'Bahamas', code: 'BS' },
  { id: '19', name: 'Bangladés', code: 'BD' },
  { id: '20', name: 'Barbados', code: 'BB' },
  { id: '21', name: 'Baréin', code: 'BH' },
  { id: '22', name: 'Bélgica', code: 'BE' },
  { id: '23', name: 'Belice', code: 'BZ' },
  { id: '24', name: 'Benín', code: 'BJ' },
  { id: '25', name: 'Bermudas', code: 'BM' },
  { id: '26', name: 'Bielorrusia', code: 'BY' },
  { id: '27', name: 'Bolivia', code: 'BO' },
  { id: '28', name: 'Bonaire, San Eustaquio y Saba', code: 'BQ' },
  { id: '29', name: 'Bosnia y Herzegovina', code: 'BA' },
  { id: '30', name: 'Botsuana', code: 'BW' },
  { id: '31', name: 'Brasil', code: 'BR' },
  { id: '32', name: 'Brunéi', code: 'BN' },
  { id: '33', name: 'Bulgaria', code: 'BG' },
  { id: '34', name: 'Burkina Faso', code: 'BF' },
  { id: '35', name: 'Burundi', code: 'BI' },
  { id: '36', name: 'Bután', code: 'BT' },
  { id: '37', name: 'Cabo Verde', code: 'CV' },
  { id: '38', name: 'Camboya', code: 'KH' },
  { id: '39', name: 'Camerún', code: 'CM' },
  { id: '40', name: 'Canadá', code: 'CA' },
  { id: '41', name: 'Catar', code: 'QA' },
  { id: '42', name: 'Chad', code: 'TD' },
  { id: '43', name: 'Chile', code: 'CL' },
  { id: '44', name: 'China', code: 'CN' },
  { id: '45', name: 'Chipre', code: 'CY' },
  { id: '46', name: 'Colombia', code: 'CO' },
  { id: '47', name: 'Comoras', code: 'KM' },
  { id: '48', name: 'Corea del Norte', code: 'KP' },
  { id: '49', name: 'Corea del Sur', code: 'KR' },
  { id: '50', name: 'Costa de Marfil', code: 'CI' },
  { id: '51', name: 'Costa Rica', code: 'CR' },
  { id: '52', name: 'Croacia', code: 'HR' },
  { id: '53', name: 'Cuba', code: 'CU' },
  { id: '54', name: 'Curazao', code: 'CW' },
  { id: '55', name: 'Dinamarca', code: 'DK' },
  { id: '56', name: 'Dominica', code: 'DM' },
  { id: '57', name: 'Ecuador', code: 'EC' },
  { id: '58', name: 'Egipto', code: 'EG' },
  { id: '59', name: 'El Salvador', code: 'SV' },
  { id: '60', name: 'Emiratos Árabes Unidos', code: 'AE' },
  { id: '61', name: 'Eritrea', code: 'ER' },
  { id: '62', name: 'Eslovaquia', code: 'SK' },
  { id: '63', name: 'Eslovenia', code: 'SI' },
  { id: '64', name: 'España', code: 'ES' },
  { id: '65', name: 'Estados Unidos', code: 'US' },
  { id: '66', name: 'Estonia', code: 'EE' },
  { id: '67', name: 'Etiopía', code: 'ET' },
  { id: '68', name: 'Filipinas', code: 'PH' },
  { id: '69', name: 'Finlandia', code: 'FI' },
  { id: '70', name: 'Fiyi', code: 'FJ' },
  { id: '71', name: 'Francia', code: 'FR' },
  { id: '72', name: 'Gabón', code: 'GA' },
  { id: '73', name: 'Gambia', code: 'GM' },
  { id: '74', name: 'Georgia', code: 'GE' },
  { id: '75', name: 'Ghana', code: 'GH' },
  { id: '76', name: 'Gibraltar', code: 'GI' },
  { id: '77', name: 'Granada', code: 'GD' },
  { id: '78', name: 'Grecia', code: 'GR' },
  { id: '79', name: 'Groenlandia', code: 'GL' },
  { id: '80', name: 'Guadalupe', code: 'GP' },
  { id: '81', name: 'Guam', code: 'GU' },
  { id: '82', name: 'Guatemala', code: 'GT' },
  { id: '83', name: 'Guayana Francesa', code: 'GF' },
  { id: '84', name: 'Guernsey', code: 'GG' },
  { id: '85', name: 'Guinea', code: 'GN' },
  { id: '86', name: 'Guinea-Bisáu', code: 'GW' },
  { id: '87', name: 'Guinea Ecuatorial', code: 'GQ' },
  { id: '88', name: 'Guyana', code: 'GY' },
  { id: '89', name: 'Haití', code: 'HT' },
  { id: '90', name: 'Honduras', code: 'HN' },
  { id: '91', name: 'Hong Kong', code: 'HK' },
  { id: '92', name: 'Hungría', code: 'HU' },
  { id: '93', name: 'India', code: 'IN' },
  { id: '94', name: 'Indonesia', code: 'ID' },
  { id: '95', name: 'Irak', code: 'IQ' },
  { id: '96', name: 'Irán', code: 'IR' },
  { id: '97', name: 'Irlanda', code: 'IE' },
  { id: '98', name: 'Isla Bouvet', code: 'BV' },
  { id: '99', name: 'Isla de Man', code: 'IM' },
  { id: '100', name: 'Isla de Navidad', code: 'CX' },
  { id: '101', name: 'Islandia', code: 'IS' },
  { id: '102', name: 'Islas Caimán', code: 'KY' },
  { id: '103', name: 'Islas Cocos', code: 'CC' },
  { id: '104', name: 'Islas Cook', code: 'CK' },
  { id: '105', name: 'Islas Feroe', code: 'FO' },
  { id: '106', name: 'Islas Georgias del Sur y Sandwich del Sur', code: 'GS' },
  { id: '107', name: 'Islas Heard y McDonald', code: 'HM' },
  { id: '108', name: 'Islas Malvinas', code: 'FK' },
  { id: '109', name: 'Islas Marianas del Norte', code: 'MP' },
  { id: '110', name: 'Islas Marshall', code: 'MH' },
  { id: '111', name: 'Islas Pitcairn', code: 'PN' },
  { id: '112', name: 'Islas Salomón', code: 'SB' },
  { id: '113', name: 'Islas Turcas y Caicos', code: 'TC' },
  { id: '114', name: 'Islas ultramarinas de Estados Unidos', code: 'UM' },
  { id: '115', name: 'Islas Vírgenes Británicas', code: 'VG' },
  { id: '116', name: 'Islas Vírgenes de los Estados Unidos', code: 'VI' },
  { id: '117', name: 'Israel', code: 'IL' },
  { id: '118', name: 'Italia', code: 'IT' },
  { id: '119', name: 'Jamaica', code: 'JM' },
  { id: '120', name: 'Japón', code: 'JP' },
  { id: '121', name: 'Jersey', code: 'JE' },
  { id: '122', name: 'Jordania', code: 'JO' },
  { id: '123', name: 'Kazajistán', code: 'KZ' },
  { id: '124', name: 'Kenia', code: 'KE' },
  { id: '125', name: 'Kirguistán', code: 'KG' },
  { id: '126', name: 'Kiribati', code: 'KI' },
  { id: '127', name: 'Kuwait', code: 'KW' },
  { id: '128', name: 'Laos', code: 'LA' },
  { id: '129', name: 'Lesoto', code: 'LS' },
  { id: '130', name: 'Letonia', code: 'LV' },
  { id: '131', name: 'Líbano', code: 'LB' },
  { id: '132', name: 'Liberia', code: 'LR' },
  { id: '133', name: 'Libia', code: 'LY' },
  { id: '134', name: 'Liechtenstein', code: 'LI' },
  { id: '135', name: 'Lituania', code: 'LT' },
  { id: '136', name: 'Luxemburgo', code: 'LU' },
  { id: '137', name: 'Macao', code: 'MO' },
  { id: '138', name: 'Macedonia', code: 'MK' },
  { id: '139', name: 'Madagascar', code: 'MG' },
  { id: '140', name: 'Malasia', code: 'MY' },
  { id: '141', name: 'Malaui', code: 'MW' },
  { id: '142', name: 'Maldivas', code: 'MV' },
  { id: '143', name: 'Malí', code: 'ML' },
  { id: '144', name: 'Malta', code: 'MT' },
  { id: '145', name: 'Marruecos', code: 'MA' },
  { id: '146', name: 'Martinica', code: 'MQ' },
  { id: '147', name: 'Mauricio', code: 'MU' },
  { id: '148', name: 'Mauritania', code: 'MR' },
  { id: '149', name: 'Mayotte', code: 'YT' },
  { id: '150', name: 'México', code: 'MX' },
  { id: '151', name: 'Micronesia', code: 'FM' },
  { id: '152', name: 'Moldavia', code: 'MD' },
  { id: '153', name: 'Mónaco', code: 'MC' },
  { id: '154', name: 'Mongolia', code: 'MN' },
  { id: '155', name: 'Montenegro', code: 'ME' },
  { id: '156', name: 'Montserrat', code: 'MS' },
  { id: '157', name: 'Mozambique', code: 'MZ' },
  { id: '158', name: 'Myanmar', code: 'MM' },
  { id: '159', name: 'Namibia', code: 'NA' },
  { id: '160', name: 'Nauru', code: 'NR' },
  { id: '161', name: 'Nepal', code: 'NP' },
  { id: '162', name: 'Nicaragua', code: 'NI' },
  { id: '163', name: 'Níger', code: 'NE' },
  { id: '164', name: 'Nigeria', code: 'NG' },
  { id: '165', name: 'Niue', code: 'UN' },
  { id: '166', name: 'Norfolk', code: 'NF' },
  { id: '167', name: 'Noruega', code: 'NO' },
  { id: '168', name: 'Nueva Caledonia', code: 'NC' },
  { id: '169', name: 'Nueva Zelanda', code: 'NZ' },
  { id: '170', name: 'Omán', code: 'OM' },
  { id: '171', name: 'Países Bajos', code: 'NL' },
  { id: '172', name: 'Pakistán', code: 'PK' },
  { id: '173', name: 'Palaos', code: 'PW' },
  { id: '174', name: 'Palestina', code: 'PS' },
  { id: '175', name: 'Panamá', code: 'PA' },
  { id: '176', name: 'Papúa Nueva Guinea', code: 'PG' },
  { id: '177', name: 'Paraguay', code: 'PY' },
  { id: '178', name: 'Perú', code: 'PE' },
  { id: '179', name: 'Polinesia Francesa', code: 'PF' },
  { id: '180', name: 'Polonia', code: 'PL' },
  { id: '181', name: 'Portugal', code: 'PT' },
  { id: '182', name: 'Puerto Rico', code: 'PR' },
  { id: '183', name: 'Reino Unido', code: 'GB' },
  { id: '184', name: 'República Árabe Saharaui Democrática', code: 'EH' },
  { id: '185', name: 'República Centroafricana', code: 'CF' },
  { id: '186', name: 'República Checa', code: 'CZ' },
  { id: '187', name: 'República del Congo', code: 'CG' },
  { id: '188', name: 'República Democrática del Congo', code: 'CD' },
  { id: '189', name: 'República Dominicana', code: 'DO' },
  { id: '190', name: 'Reunión', code: 'RE' },
  { id: '191', name: 'Ruanda', code: 'RW' },
  { id: '192', name: 'Rumania', code: 'RO' },
  { id: '193', name: 'Rusia', code: 'RU' },
  { id: '194', name: 'Samoa', code: 'WS' },
  { id: '195', name: 'Samoa Americana', code: 'AS' },
  { id: '196', name: 'San Bartolomé', code: 'BL' },
  { id: '197', name: 'San Cristóbal y Nieves', code: 'KN' },
  { id: '198', name: 'San Marino', code: 'SM' },
  { id: '199', name: 'San Martín', code: 'MF' },
  { id: '200', name: 'San Pedro y Miquelón', code: 'PM' },
  { id: '201', name: 'San Vicente y las Granadinas', code: 'VC' },
  { id: '202', name: 'Santa Elena, Ascensión y Tristán de Acuña', code: 'SH' },
  { id: '203', name: 'Santa Lucía', code: 'LC' },
  { id: '204', name: 'Santo Tomé y Príncipe', code: 'ST' },
  { id: '205', name: 'Senegal', code: 'SN' },
  { id: '206', name: 'Serbia', code: 'RS' },
  { id: '207', name: 'Seychelles', code: 'SC' },
  { id: '208', name: 'Sierra Leona', code: 'SL' },
  { id: '209', name: 'Singapur', code: 'SG' },
  { id: '210', name: 'Sint Maarten', code: 'SX' },
  { id: '211', name: 'Siria', code: 'SY' },
  { id: '212', name: 'Somalia', code: 'SO' },
  { id: '213', name: 'Sri Lanka', code: 'LK' },
  { id: '214', name: 'Suazilandia', code: 'SZ' },
  { id: '215', name: 'Sudáfrica', code: 'ZA' },
  { id: '216', name: 'Sudán', code: 'SD' },
  { id: '217', name: 'Sudán del Sur', code: 'SS' },
  { id: '218', name: 'Suecia', code: 'SI' },
  { id: '219', name: 'Suiza', code: 'CH' },
  { id: '220', name: 'Surinam', code: 'SR' },
  { id: '221', name: 'Svalbard y Jan Mayen', code: 'SJ' },
  { id: '222', name: 'Tailandia', code: 'TH' },
  { id: '223', name: 'Taiwán (República de China)', code: 'TW' },
  { id: '224', name: 'Tanzania', code: 'TZ' },
  { id: '225', name: 'Tayikistán', code: 'TJ' },
  { id: '226', name: 'Territorio Británico del Océano Índico', code: 'IO' },
  { id: '227', name: 'Tierras Australes y Antárticas Francesas', code: 'TF' },
  { id: '228', name: 'Timor Oriental', code: 'TL' },
  { id: '229', name: 'Togo', code: 'TG' },
  { id: '230', name: 'Tokelau', code: 'TK' },
  { id: '231', name: 'Tonga', code: 'TO' },
  { id: '232', name: 'Trinidad y Tobago', code: 'TT' },
  { id: '233', name: 'Túnez', code: 'TN' },
  { id: '234', name: 'Turkmenistán', code: 'TM' },
  { id: '235', name: 'Turquía', code: 'TR' },
  { id: '236', name: 'Tuvalu', code: 'TV' },
  { id: '237', name: 'Ucrania', code: 'UA' },
  { id: '238', name: 'Uganda', code: 'UG' },
  { id: '239', name: 'Uruguay', code: 'UY' },
  { id: '240', name: 'Uzbekistán', code: 'UZ' },
  { id: '241', name: 'Vanuatu', code: 'VU' },
  { id: '242', name: 'Vaticano, Ciudad del', code: 'VA' },
  { id: '243', name: 'Venezuela', code: 'VE' },
  { id: '244', name: 'Vietnam', code: 'VN' },
  { id: '245', name: 'Wallis y Futuna', code: 'WF' },
  { id: '246', name: 'Yemen', code: 'YE' },
  { id: '247', name: 'Yibuti', code: 'DJ' },
  { id: '248', name: 'Zambia', code: 'ZM' },
  { id: '249', name: 'Zimbabue', code: 'ZW' },
];
