/**
 * Conceptos Exogena DIAN
 * Total: 364 conceptos
 * Generado automaticamente desde Supabase
 */

export const exogenousConcepts: { format_code: string; code: string; name: string }[] = [
  { format_code: '1003', code: '1301', name: "Retenciones por salarios y demàs pagos laborales" },
  { format_code: '1003', code: '1302', name: "Retenciones por ventas" },
  { format_code: '1003', code: '1303', name: "Retenciones por Servicios" },
  { format_code: '1003', code: '1304', name: "Retenciones por Honorarios" },
  { format_code: '1003', code: '1305', name: "Retenciones por Comisiones" },
  { format_code: '1003', code: '1306', name: "Retenciones por Intereses y Rendimientos Financieros" },
  { format_code: '1003', code: '1307', name: "Retenciones por Arrendamientos" },
  { format_code: '1003', code: '1308', name: "Retencion por Otros conceptos" },
  { format_code: '1003', code: '1309', name: "Retención en la fuente en el  Impuesto a las ventas." },
  { format_code: '1003', code: '1310', name: "Retención por dividendos y participaciones" },
  { format_code: '1003', code: '1311', name: "Retención por enajenación de activos fijos de personas naturales ante oficinas de tránsito y otras entidades autorizadas" },
  { format_code: '1003', code: '1312', name: "Retención por ingresos de tarjetas débito y crédito" },
  { format_code: '1003', code: '1313', name: "Retención por loterías, rifas, apuestas y similares" },
  { format_code: '1003', code: '1314', name: "Retención por Impuesto de Timbre" },
  { format_code: '1003', code: '1320', name: "Retención por dividendos y participaciones recibidas por sociedades nacionales art. 242-1 del E.T." },
  { format_code: '1007', code: '4001', name: "Ingresos Brutos de Actividades Ordinarias" },
  { format_code: '1007', code: '4002', name: "Otros Ingresos Brutos" },
  { format_code: '1007', code: '4003', name: "Ingresos por intereses y rendimientos financieros" },
  { format_code: '1007', code: '4004', name: "Ingresos por intereses Correspondientes a Creditos Hipotecarios" },
  { format_code: '1007', code: '4005', name: "Ingresos a traves de Consorcios o Uniones Temporales" },
  { format_code: '1007', code: '4006', name: "Ingresos a traves de Mandato o Administracion Delegada" },
  { format_code: '1007', code: '4007', name: "Ingresos a traves de Exploracion y Explotacion de Hidrocarburos, Gases y Minerales" },
  { format_code: '1007', code: '4008', name: "Ingresos a traves de Fiducia" },
  { format_code: '1007', code: '4009', name: "Ingresos a traves de Terceros (Beneficiario)" },
  { format_code: '1007', code: '4011', name: "Ingresos a traves de joint venture" },
  { format_code: '1007', code: '4012', name: "Ingresos a traves de Cuentas en Participacion" },
  { format_code: '1007', code: '4013', name: "Ingresos a traves de Convenios de Cooperacion con Entidades Publicas" },
  { format_code: '1007', code: '4014', name: "Ingresos por ventas con puntos premio redimidos en el período, procedentes de programas de fidelización" },
  { format_code: '1007', code: '4015', name: "Ingresos por puntos premio vencidos y no reclamados en el periodo, procedentes de programas de fidelización, artículo 28 numeral 8 del Estatuto Tributario. Se debe reportar con el NIT del informante." },
  { format_code: '1007', code: '4016', name: "Ingresos por ventas con puntos premio redimidos en el período, incluidos en el concepto 4015 que corresponden en años anteriores, en virtud de la aplicación del artículo 28 numeral 8 del Estatuto Tributario. Se debe reportar con el NIT del informante." },
  { format_code: '1007', code: '4017', name: "Ingresos por recuperaciones de costos y deducciones que constituyen renta líquida. Art.195 al 198 E.T. Las transacciones donde no se identifique un tercero informado se deben reportar con el NIT del informante." },
  { format_code: '1007', code: '4018', name: "Ingresos por diferencia en cambio. Se debe reportar con el NIT del informante." },
  { format_code: '1007', code: '4019', name: "Ingresos brutos constitutivos de ganancia ocasional" },
  { format_code: '1007', code: '4020', name: "Ingresos brutos por venta de acciones de sociedades o compañías que no cotizan en bolsa que constituyan renta. (incluye las acciones recibidas por cesión y donación)." },
  { format_code: '1007', code: '4021', name: "Ingresos brutos por venta de acciones de sociedades o compañías que no cotizan en bolsa que constituyan ganancia ocasional. (incluye las acciones recibidas por cesión y donación)." },
  { format_code: '1001', code: '5002', name: "Honorarios" },
  { format_code: '1001', code: '5003', name: "Comisiones" },
  { format_code: '1001', code: '5004', name: "Servicios" },
  { format_code: '1001', code: '5005', name: "Arrendamientos" },
  { format_code: '1001', code: '5006', name: "Intereses y rendimientos financieros causados" },
  { format_code: '1001', code: '5007', name: "Compra de activos movibles (E.T.Art 60)" },
  { format_code: '1001', code: '5008', name: "Compra de Activos Fijos (E.T. Art 60)" },
  { format_code: '1001', code: '5010', name: "Pagos o Abonos en cuenta por concepto de aportes parafiscales al SENA, a las Cajas de Compensación Familiar y al Instituto Colombiano de Bienestar Familiar" },
  { format_code: '1001', code: '5011', name: "Pagos o abonos en cuenta efectuado a las empresas promotoras de salud EPS y los aportes al Sistema de Riesgos Laborales, incluidos los aportes del trabajador" },
  { format_code: '1001', code: '5012', name: "Pagos  o abonos  en  cuenta  por concepto de aportes obligatorios para pensiones efectuados a los Fondos de Pensiones, incluidos los aportes del trabajador" },
  { format_code: '1001', code: '5013', name: "Donaciones en dinero efectuadas a las entidades señaladas en los artículos 125, 125-4,126-2 y 158-1 del Estatuto Tributario y la establecida en el artículo 16 de la Ley 814 de 2003, y demás que determine la ley" },
  { format_code: '1001', code: '5014', name: "Donaciones en activos diferentes a dinero efectuadas a las entidades señaladas en los artículos 125, 125-4,126-2 y 158-1 del Estatuto Tributario y la establecida en el artículo 16 de la Ley 814 de 2003, y demás que determine la ley" },
  { format_code: '1001', code: '5015', name: "El valor de los impuestos solicitados como deducción" },
  { format_code: '1001', code: '5016', name: "Los demás costos y deducciones" },
  { format_code: '1001', code: '5018', name: "Importe de las primas de reaseguros pagados o abonados en cuenta" },
  { format_code: '1001', code: '5019', name: "El monto de las amortizaciones realizadas" },
  { format_code: '1001', code: '5020', name: "Compra de activos fijos reales productivos sobre los cuales solicitó deducción, art. 158-3 E.T. El valor acumulado pagado o abonado en cuenta" },
  { format_code: '1001', code: '5023', name: "Valor  acumulado  de  los  pagos  o  abonos  en  cuenta  al  exterior  por  asistencia  técnica" },
  { format_code: '1001', code: '5024', name: "Valor acumulado de los pagos o abonos en cuenta al exterior por marcas" },
  { format_code: '1001', code: '5025', name: "Valor acumulado de los pagos o abonos en cuenta al exterior por patentes" },
  { format_code: '1001', code: '5026', name: "valor acumulado de los pagos o abonos en cuenta al exterior por regalías" },
  { format_code: '1001', code: '5027', name: "Valor acumulado de los pagos o abonos en cuenta al exterior por servicios técnicos" },
  { format_code: '1001', code: '5028', name: "El valor acumulado de la devolución de pagos o abonos en cuenta y retenciones correspondientes a operaciones de años anteriores." },
  { format_code: '1001', code: '5029', name: "Gastos pagados por anticipado por Compras" },
  { format_code: '1001', code: '5030', name: "Gastos pagados por anticipado por Honorarios" },
  { format_code: '1001', code: '5031', name: "Gastos pagados por anticipado por Comisiones" },
  { format_code: '1001', code: '5032', name: "Gastos pagados por anticipado por Servicios" },
  { format_code: '1001', code: '5033', name: "Gastos pagados por anticipado por Arrendamientos" },
  { format_code: '1001', code: '5034', name: "Gastos pagados por anticipado por intereses y rendimientos financieros" },
  { format_code: '1001', code: '5035', name: "Gastos pagados por anticipado por otros conceptos" },
  { format_code: '1001', code: '5044', name: "El pago por loterías, rifas, apuestas y similares" },
  { format_code: '1001', code: '5045', name: "Retención sobre ingresos de tarjetas débito y crédito" },
  { format_code: '1001', code: '5046', name: "Enajenación de activos fijos de personas naturales ante oficinas de tránsito y otras entidades autorizadas" },
  { format_code: '1001', code: '5047', name: "Importe de los siniestros por lucro cesante pagados o abonados en cuenta" },
  { format_code: '1001', code: '5048', name: "Importe de los siniestros por daño emergente pagados o abonados en cuenta" },
  { format_code: '1001', code: '5053', name: "Retenciones practicas a titulo de timbre" },
  { format_code: '1001', code: '5054', name: "La devolución de retenciones a título de impuesto de timbre, correspondientes a operaciones de años anteriores" },
  { format_code: '1001', code: '5055', name: "Viaticos" },
  { format_code: '1001', code: '5056', name: "Gastos de representacion" },
  { format_code: '1001', code: '5058', name: "Valor de los Aportes, Tasas y Contribuciones solicitado como deducción" },
  { format_code: '1001', code: '5059', name: "El  pago  o  abono  en cuenta  realizado  a  cada  uno  de  los  cooperados,  del  valor  del  Fondo  para revalorización de aportes" },
  { format_code: '1001', code: '5060', name: "Redención de inversiones en lo que corresponde al reembolso del capital por titulos de capitalizacion" },
  { format_code: '1001', code: '5061', name: "Utilidades Pagadas o abonadas en cuenta, cuando el beneficiario es diferente al fideicomitente" },
  { format_code: '1001', code: '5063', name: "Intereses y rendimientos financieros efectivamente pagados" },
  { format_code: '1001', code: '5064', name: "Devoluciones de saldos de aportes pensionales pagados" },
  { format_code: '1001', code: '5065', name: "Excedentes pensionales de libre disponibilidad componente de capital pagados" },
  { format_code: '1001', code: '5066', name: "El valor del impuesto nacional al consumo" },
  { format_code: '1001', code: '5067', name: "El valor acumulado de los pagos o abonos en cuenta al exterior por consultoría" },
  { format_code: '1001', code: '5068', name: "Participaciones o dividendos pagados o abonados en cuenta en calidad de exigibles correspondientes a 2016 y anteriores, parágrafo 2 artículo 49 E.T." },
  { format_code: '1001', code: '5069', name: "Participaciones o dividendos pagados o abonados en cuenta en calidad de exigibles correspondientes a 2016 y anteriores, numeral 3 del artículo 49 E.T." },
  { format_code: '1001', code: '5070', name: "Participaciones o dividendos pagados o abonados en cuenta en calidad de exigibles correspondientes a 2017 y siguientes, parágrafo 2 artículo 49 E.T." },
  { format_code: '1001', code: '5071', name: "Participaciones o dividendos pagados o abonados en cuenta en calidad de exigibles correspondientes a 2017 y siguientes, numeral 3 del artículo 49 E.T." },
  { format_code: '1001', code: '5072', name: "El importe de los siniestros por seguros de vida pagados o abonados en cuenta" },
  { format_code: '1001', code: '5073', name: "Desembolsos por depósitos judiciales. Se debe identificar al beneficiario" },
  { format_code: '1001', code: '5074', name: "Desembolsos por reintegros de depósitos judiciales. Se debe identificar al beneficiario" },
  { format_code: '1001', code: '5075', name: "Regalías y explotación de la propiedad intelectual" },
  { format_code: '1001', code: '5076', name: "Valor de utilidades distribuidas provenientes de diferimiento de ingresos, inciso 4 del art. 23-1 del E.T." },
  { format_code: '1001', code: '5079', name: "Intereses por deuda a vinculados en subcapitalización art.118-1 E.T." },
  { format_code: '1001', code: '5080', name: "El valor acumulado de los pagos o abonos efectuados a proveedores del exterior por servicios audiovisuales digitales (entre otros, de música, videos, películas y juegos de cualquier tipo, así como la radiodifusión de cualquier tipo de evento).Art.437-2 num.8 E.T." },
  { format_code: '1001', code: '5081', name: "El valor acumulado de los pagos o abonos efectuados a proveedores del exterior por servicios prestados a través de plataformas digitales. Art.437-2 num.8 E.T." },
  { format_code: '1001', code: '5082', name: "El valor acumulado de los pagos o abonos efectuados a proveedores del exterior por suministro de servicios de publicidad online. Art.437-2 num.8 E.T." },
  { format_code: '1001', code: '5083', name: "El valor acumulado de los pagos o abonos efectuados a proveedores del exterior por suministro de enseñanza o entrenamiento a distancia. Art.437-2 num.8 E.T." },
  { format_code: '1001', code: '5084', name: "El valor acumulado de los pagos o abonos efectuados a proveedores del exterior por suministro de derechos de uso o explotación de intangibles. Art.437-2 num.8 E.T." },
  { format_code: '1001', code: '5085', name: "El valor acumulado de los pagos o abonos efectuados a proveedores del exterior por Otros servicios electrónicos o digitales con destino a usuarios ubicados en Colombia. Art.437-2 num.8 E.T." },
  { format_code: '1001', code: '5086', name: "Valor retención en la fuente trasladada a terceros por participaciones o dividendos recibidos de sociedades nacionales E.T. art. 242-1 par.1" },
  { format_code: '1001', code: '5087', name: "Valor de los puntos premio redimidos en el período que afectan el gasto directamente, procedentes de programas de fidelización." },
  { format_code: '1001', code: '5088', name: "Costos y gastos por diferencia en cambio.Se debe repoortar con el NIT del informante" },
  { format_code: '1001', code: '5089', name: "Valor Compra de acciones de sociedades que no cotizan en bolsa" },
  { format_code: '1001', code: '5090', name: "Valor Donación de acciones de sociedades que no cotizan en bolsa" },
  { format_code: '1001', code: '5091', name: "Valor cesión de acciones de sociedades que no cotizan en bolsa" },
  { format_code: '1001', code: '5092', name: "Valor del pago que constituye ingreso en especie para el beneficio Art 29-1E. T" },
  { format_code: '1001', code: '5093', name: "Donaciones de bebidas ultraprocesadas y azucaradas a los bancos de alimentos por los responsables del impuesto a estos bienes ET art 513-1, par 5 adicionado por el art 54 L 2277/2022" },
  { format_code: '1001', code: '5094', name: "Donaciones de productos comestibles ultraprocesados industrialmente y/o con alto contenido de azucares añadidos, sodio o grasas saturadas a los bancos de alimentos por los responsables del impuesto a estos bienes ET art 513-1, par 5 adicionado por el art 54 L 2277/2022" },
  { format_code: '1001', code: '5095', name: "Pago por concepto de regalías pagadas a la Nación u otros entes territoriales por la explotación de hidrocarburos por entes diferentes a los organismos descentralizados. ET art 115 par 1" },
  { format_code: '1001', code: '5096', name: "Pago por concepto de regalías pagadas a la Nación u otros entes territoriales por la explotación de gas por entes diferentes a los organismos descentralizados. ET art 115 par 1" },
  { format_code: '1001', code: '5097', name: "Pago por concepto de regalías pagadas a la nación u otros entes territoriales por la explotación de carbón por entes diferentes a los organismos descentralizados. ET art 115 par 1" },
  { format_code: '1001', code: '5098', name: "Pago por concepto de regalías pagadas a la Nación u otros entes territoriales por la explotación de otros minerales y piedras preciosas por entes diferentes a los organismos descentralizados. ET art 115 par 1" },
  { format_code: '1001', code: '5099', name: "Pago por concepto de regalías pagadas a la Nación u otros entes territoriales por la explotación de sal y materiales de construcción por entes diferentes a los organismos descentralizados. ET art 115 par 1" },
  { format_code: '1001', code: '5100', name: "Valor del Pago o abono en cuenta por prima en colocación de acciones y otros conceptos patrimoniales, sin incluir los reembolsos de aportes." },
  { format_code: '1008', code: '1315', name: "Saldo de las cuentas por cobrar a clientes" },
  { format_code: '1008', code: '1316', name: "Saldo de las cuentas por cobrar a accionistas, socios, comuneros, cooperados y compañías vinculadas" },
  { format_code: '1008', code: '1317', name: "Otras Cuentas por Cobrar" },
  { format_code: '1008', code: '1318', name: "Valor total del saldo fiscal del deterioro de cartera, identificándolo con el NIT del deudor" },
  { format_code: '1012', code: '1110', name: "Saldo a 31 de Diciembre de las cuentas corrientes y/o ahorro que posea en el país" },
  { format_code: '1012', code: '1115', name: "Valor total del saldo de las cuentas corrientes y/o ahorro poseídas en el exterior" },
  { format_code: '1012', code: '1200', name: "Valor Patrimonial de los Bonos" },
  { format_code: '1012', code: '1201', name: "Valor Patrimonial de los Certificados de Depósito" },
  { format_code: '1012', code: '1202', name: "Valor Patrimonial de los Títulos" },
  { format_code: '1012', code: '1203', name: "Valor Patrimonial de los Derechos Fiduciarios" },
  { format_code: '1012', code: '1204', name: "Valor Patrimonial de las Demás Inversiones Poseídas" },
  { format_code: '1012', code: '1205', name: "Valor Patrimonial de las Acciones o Aportes poseidos a 31 de Diciembre" },
  { format_code: '1012', code: '1206', name: "Valor patrimonial de los criptoactivos" },
  { format_code: '1011', code: '1105', name: "Saldo a 31 de Diciembre en caja" },
  { format_code: '1011', code: '1502', name: "Valor patrimonial de vehiculos, maquinaria y equipo." },
  { format_code: '1011', code: '1512', name: "Valor patrimonial de activos fijos intangibles" },
  { format_code: '1011', code: '1513', name: "Valor patrimonial de los activos fijos agotables" },
  { format_code: '1011', code: '1519', name: "Valor Patrimonial a 31 de diciembre de Activos Biológicos Plantas" },
  { format_code: '1011', code: '1520', name: "Valor Patrimonial a 31 de diciembre de Activos Biológicos Animales" },
  { format_code: '1011', code: '1521', name: "Valor Patrimonial de la casa o apartamento de habitación (inciso 2 art 295-3ET)" },
  { format_code: '1011', code: '1522', name: "Valor Patrimonial de lotes rurales y fincas" },
  { format_code: '1011', code: '1523', name: "Valor Patrimonial de lotes urbanos" },
  { format_code: '1011', code: '1524', name: "Valor Patrimonial de otros bienes inmuebles. (No relacionados en los conceptos 1512, 1513y 1519)" },
  { format_code: '1011', code: '1525', name: "Valor Patrimonial de otros bienes muebles." },
  { format_code: '1011', code: '1526', name: "Valor Patrimonial de otros activos. (No relacionados en los artículos 29 y 30 de la presente resolución y en los conceptos de este articulo)" },
  { format_code: '1011', code: '1601', name: "Inversiones Zomac realizadas en el año representadas en inventarios, propiedad planta y equipo y otras inversiones" },
  { format_code: '1011', code: '1602', name: "Inversiones en Megainversiones en el año representadas en propiedad, planta y equipo." },
  { format_code: '1011', code: '1603', name: "Inversiones realizadas por empresas de economía naranja de que trata el numeral 1 del artículo 235-2 del E.T., en propiedad, planta y equipo, intangibles de que trata el numeral 1 del artículo 74 e inversiones del numeral 3 del artículo 74-1, del E.T" },
  { format_code: '1011', code: '1604', name: "Inversiones realizadas por empresas dedicas al desarrollo del campo colombiano de que trata el numeral 2 del artículo 235-2 del E.T., en propiedad, planta y equipo y activos biológicos productores" },
  { format_code: '1011', code: '8104', name: "Renta exenta por venta energía eléctrica generada con base en energía eólica, biomasa o residuos agrícolas, solar, geotérmica o de los mares. Art.235-2 numeral 3." },
  { format_code: '1011', code: '8106', name: "Renta exenta por aprovechamiento de nuevas plantaciones forestales incluida la guadua el caucho y el marañón. Art. 235-2 numeral 5_x000D_, Inciso 1" },
  { format_code: '1011', code: '8109', name: "Renta exenta por prestación de servicio de transporte fluvial con embarcaciones y planchones de bajo calado Art. 235-2 numeral 6." },
  { format_code: '1011', code: '8111', name: "Rentas exentas por la utilidad en la enajenación de predios destinados a fines de utilidad pública. Num 9 Art. 207-2 E.T. Sentencia C-083 del 2018" },
  { format_code: '1011', code: '8120', name: "Rentas exentas por aplicación de algún convenio para evitar la doble tributación." },
  { format_code: '1011', code: '8121', name: "Renta exenta por creaciones literarias dela economía naranja contenidas en el artículo 28 de la Ley 98 de 1993. Art. 235-2 numeral 8." },
  { format_code: '1011', code: '8125', name: "Rentas exentas por Intereses, comisiones y pagos por deuda pública externa, E.T. art. 218 E.T." },
  { format_code: '1011', code: '8127', name: "Rentas exentas por inversión en nuevos aserríos, plantas de procesamiento y plantaciones de árboles maderables y árboles en producción de frutos. E.T., art. 235-2, numeral 5.Incisos 2 y 3" },
  { format_code: '1011', code: '8133', name: "Rentas exentas por servicios prestados en hoteles nuevos. E.T., Art. 207-2, Num 3 Sentencia C 235 del 29 de mayo de 2019" },
  { format_code: '1011', code: '8134', name: "Rentas exentas por servicios prestados en hoteles remodelado y/o ampliados. E.T., Art. 207-2 E.T, Num. 4. Sentencia C 235 del 29 de mayo de 2019" },
  { format_code: '1011', code: '8140', name: "Rentas exentas por aportes voluntarios a los fondos de pensiones. E.T. art. 126-1, inc. 2" },
  { format_code: '1011', code: '8141', name: "Rentas exentas por los ahorros a largo plazo para el fomento de la construcción. E.T., art. 126-4." },
  { format_code: '1011', code: '8142', name: "Rentas exentas del beneficio neto o excedente para las entidades sin ánimo de lucro. E.T., art 358 E.T." },
  { format_code: '1011', code: '8145', name: "Rentas exentas de fondos provenientes de auxilios o donaciones de entidades o gobiernos extranjeros. Convenidos con el Gobierno colombiano, destinados a programas de utilidad común y registrados por la Agencia Presidencial de la Cooperación Internacional. Art. 96 L. 788/2002" },
  { format_code: '1011', code: '8156', name: "Rentas exentas prestaciones provenientes de un fondo de pensiones. E.T. art. 207." },
  { format_code: '1011', code: '8159', name: "Renta exenta pago principal y demás rendimientos generados en actividades financieras por parte de entidades gubernamentales de carácter financiero y de cooperación para el desarrollo. E.T., art. 207-2, numeral 12." },
  { format_code: '1011', code: '8160', name: "Rentas exentas de los industriales de la cinematografía, personas naturales. L. 397/1997, art. 46." },
  { format_code: '1011', code: '8164', name: "Renta exenta por la utilidad en la enajenación de predios destinados al desarrollo de proyectos de vivienda interés social y/o prioritario. Art. 235-2 numeral 4, literal a)" },
  { format_code: '1011', code: '8165', name: "Renta exenta por la utilidad en la primera enajenación de viviendas de interés social y/o prioritario. E.T., art. 235-2, numeral 4, literal b)." },
  { format_code: '1011', code: '8167', name: "Renta exenta de que trata L. 546/1999, art. 16. Modificado. L. 964/2005 asociados a proyectos de vivienda de interés y prioritario. E.T., art. 235-2, numeral 4, literal d)." },
  { format_code: '1011', code: '8168', name: "Renta exenta por rendimientos financieros provenientes de créditos para adquisición de vivienda de interés social y/o prioritario. E.T., art. 235-2, numeral 4 literal e)" },
  { format_code: '1011', code: '8169', name: "Renta exenta por los rendimientos generados por la reserva de estabilización que constituyen las entidades administradoras de fondos de pensiones y cesantías. Art. 101 de la Ley 100 de 1993.  Art. 235-2 numeral 9." },
  { format_code: '1011', code: '8171', name: "Renta exenta. Incentivo tributario para empresas de economía naranja E.T., Art. 235-2 numeral 1, E.T." },
  { format_code: '1011', code: '8172', name: "Renta exenta. Incentivo tributario para el desarrollo del campo colombiano E.T., Art. 235-2 numeral 2, E.T." },
  { format_code: '1011', code: '8173', name: "Renta exenta de capital por dividendos o participaciones distribuidos por no residentes a CHC y por prima en colocación de acciones. Art.895 E.T.." },
  { format_code: '1011', code: '8174', name: "Renta exenta ganancia ocasional derivada de la venta o transmisión de la participación de una CHC en entidades no residentes. Art. 896 E.T" },
  { format_code: '1011', code: '8175', name: "Renta exenta de las sumas destinadas al pago de los seguros de invalidez y de sobrevivientes dentro del mismo régimen de ahorro individual con solidaridad. L. 100/93, art. 135" },
  { format_code: '1011', code: '8176', name: "Rentas exentas provenientes de bienes inmuebles situados en otro país de la CAN. Decisión 578 de 2004, art. 4" },
  { format_code: '1011', code: '8177', name: "Rentas exentas provenientes de la explotación de recursos naturales en otro país de la CAN . Decisión 578 de 2004, art. 5" },
  { format_code: '1011', code: '8178', name: "Rentas exentas por actividades empresariales efectuadas en otro país de la CAN. Decisión 578 de 2004, art. 6" },
  { format_code: '1011', code: '8179', name: "Rentas exentas de empresas de transporte domiciliadas en otro país de la CAN. Decisión 578 de 2004, art. 8" },
  { format_code: '1011', code: '8180', name: "Rentas exentas por regalías de bienes intangibles en un país miembro de la CAN. Decisión 578 de 2004, art. 9" },
  { format_code: '1011', code: '8181', name: "Rentas exentas por intereses y demás rendimientos financieros cuyo pago se registra e imputa en otro país miembro de la CAN. Decisión 578 de 2004, art. 10" },
  { format_code: '1011', code: '8182', name: "Rentas exentas por dividendos y participaciones distribuidos por empresas domiciliadas en otro país miembro de la CAN. Decisión 578 de 2004, art. 11." },
  { format_code: '1011', code: '8183', name: "Rentas exentas por ganancias de capital obtenidas en la venta de bienes situados en otro país miembro de la CAN. Decisión 578 de 2004, art. 12" },
  { format_code: '1011', code: '8184', name: "Renta exenta generados por la prestación de servicios personales prestados en otro país miembro de la CAN. Decisión 578 de 2004, art. 13." },
  { format_code: '1011', code: '8185', name: "Rentas exentas por beneficios empresariales en servicios, servicios técnicos, asistencia técnica y consultoría prestados en otro país de la CAN. Decisión 578 de 2004, art. 14" },
  { format_code: '1011', code: '8186', name: "Rentas exentas por pensiones y anualidades obtenidas de fuentes productoras situadas en otro país miembro de la CAN. . Decisión 578 de 2004, art. 15" },
  { format_code: '1011', code: '8187', name: "Rentas exentas provenientes de actividades de entretenimiento público efectuadas en otro país miembro de la CAN. Decisión 578 de 2004, art. 16" },
  { format_code: '1011', code: '8200', name: "Deducción en la declaración de renta por las inversiones realizadas en activos fijos reales productivos. E.T., Art. 158-3." },
  { format_code: '1011', code: '8207', name: "Costo o deducción por salarios, prestaciones sociales y demás pagos laborales. No debe contener los valores especificados en otros conceptos." },
  { format_code: '1011', code: '8208', name: "Deducción por pagos efectuados a la casa matriz. E.T., art. 124." },
  { format_code: '1011', code: '8209', name: "Deducción por gastos en el exterior. E.T., art. 121. No debe contener los valores especificados en el concepto 8282 ni la diferencia en cambio." },
  { format_code: '1011', code: '8210', name: "Costo en la enajenación de activos fijos poseídos por menos de dos años. E.T., art. 179." },
  { format_code: '1011', code: '8211', name: "Deducción del gravamen a los movimientos financieros. E.T., art. 115." },
  { format_code: '1011', code: '8212', name: "Deducción por agotamiento en explotación de hidrocarburos, E.T., art. 161." },
  { format_code: '1011', code: '8215', name: "Deducción por intereses sobre préstamos educativos del Icetex y para adquisición de vivienda. E.T., art. 119, modificado por L. 2010/2019, art. 89." },
  { format_code: '1011', code: '8217', name: "Deducción por donación o inversión en producción cinematográfica. L. 814/2003, art. 16." },
  { format_code: '1011', code: '8218', name: "Deducción por protección, mantenimiento y conservación muebles e inmuebles de interés cultural, L. 1185/2008, art. 14." },
  { format_code: '1011', code: '8225', name: "Deducción por donaciones del sector privado en la red nacional de bibliotecas públicas y biblioteca nacional. E.T., art 125. Modificado. L. 1819/2016, art. 75." },
  { format_code: '1011', code: '8228', name: "Costo o deducción por las reparaciones locativas realizadas sobre inmuebles." },
  { format_code: '1011', code: '8230', name: "Deducción por las inversiones realizadas en librerías. L. 98/1993, art. 30." },
  { format_code: '1011', code: '8231', name: "Deducción por la inversión realizada en centros de reclusión. L.633/2000, art.98" },
  { format_code: '1011', code: '8233', name: "Deducción de impuestos devengados y pagados. E.T. arts.115 y 115-1. No debe contener los valores especificados en otros conceptos." },
  { format_code: '1011', code: '8234', name: "Costo o deducción de intereses. E.T., art. 117. No debe contener los valores especificados en el concepto 8236." },
  { format_code: '1011', code: '8236', name: "Costo o deducción por contratos de leasing. E.T., art. 127-1." },
  { format_code: '1011', code: '8237', name: "Deducción por costos y gastos por campañas de publicidad de productos extranjeros. E.T., art. 88-1" },
  { format_code: '1011', code: '8238', name: "Deducción de la provisión de cartera de créditos y provisión de coeficiente de riesgo, provisiones realizadas durante el respectivo año gravable sobre bienes recibidos en dación en pago y sobre contratos de leasing. E.T., art.145, par.1. (Modificado. L. 1819/2016, art. 87)." },
  { format_code: '1011', code: '8239', name: "Deducción por deudas manifiestamente pérdidas o sin valor. E.T., art. 146." },
  { format_code: '1011', code: '8240', name: "Deducción por pérdida de activos. E.T. art. 148." },
  { format_code: '1011', code: '8241', name: "Costo o deducción por aportes al Instituto Colombiano de Bienestar Familiar, (ICBF). E.T., art. 114." },
  { format_code: '1011', code: '8242', name: "Costo o deducción por aportes a Cajas de Compensación Familiar. E.T., art. 115.1." },
  { format_code: '1011', code: '8243', name: "Costo o deducción por aportes al Servicio Nacional de Aprendizaje, (SENA). E.T., art. 114." },
  { format_code: '1011', code: '8244', name: "Deducción de contribuciones a fondos de pensiones de jubilación e invalidez y fondos de cesantías. E.T. Art. 126-1, modificado L. 1819/2016, art. 15." },
  { format_code: '1011', code: '8245', name: "Deducción por concepto de cesantías pagadas, E.T., art. 109. No debe contener los valores especificados en los conceptos 8248, 8250, 8263 y 8271." },
  { format_code: '1011', code: '8246', name: "Deducción por concepto de aportes a cesantías por los trabajadores independientes. E.T., art- 126-1, inciso 6." },
  { format_code: '1011', code: '8247', name: "Deducción por concepto de contribuciones parafiscales agropecuarias efectuadas por los productores a los fondos de estabilización de la L. 101/1993. art 29" },
  { format_code: '1011', code: '8248', name: "Deducción por salarios, prestaciones sociales y demás pagos laborales, pagados a viudas y huérfanos de miembros de las Fuerzas Armadas muertos en combate, secuestrados o desaparecidos. Art. 108-1 del E.T." },
  { format_code: '1011', code: '8249', name: "Costo o deducción por apoyo de sostenimiento mensual de los trabajadores contratados como aprendices. L.115/1994, art. 189." },
  { format_code: '1011', code: '8250', name: "Costo o deducción por salarios pagados, durante el cautiverio, a sus empleados víctimas de secuestros. L. 986/2005, art. 21." },
  { format_code: '1011', code: '8255', name: "Costo o deducción por pagos a terceros por concepto de alimentación del trabajador y su familia o suministro de alimentación para los mismos." },
  { format_code: '1011', code: '8256', name: "Costo o deducción por el pago de estudios a trabajadores en instituciones de educación superior. L. 30/1992, art. 124" },
  { format_code: '1011', code: '8257', name: "Deducción por factor especial de agotamiento en explotación de hidrocarburos, E.T. art. 166." },
  { format_code: '1011', code: '8259', name: "Deducción por tasas y contribuciones fiscales pagadas Art 115 ET" },
  { format_code: '1011', code: '8261', name: "Deducción de la provisión para el pago de futuras pensiones.  E.T., art. 112." },
  { format_code: '1011', code: '8263', name: "Costo o deducción por salarios y prestaciones sociales a trabajadores con discapacidad no inferior al 25%. L.361/1997, art. 31." },
  { format_code: '1011', code: '8265', name: "Deducción por aumento en la reserva técnica de FOGAFIN Y FOGACOOP. E.T., art. 19-3." },
  { format_code: '1011', code: '8271', name: "Deducción por salarios y prestaciones sociales pagados a mujeres víctimas de violencia comprobada. L. 1257/2008, art. 23." },
  { format_code: '1011', code: '8272', name: "Deducción del 100% por inversiones en infraestructura para la realización de espectáculos públicos. Art. 4 L. 1493/11." },
  { format_code: '1011', code: '8273', name: "Deducción por inversiones en jardines botánicos. L. 299/1996, art. 12" },
  { format_code: '1011', code: '8274', name: "Deducción por inversiones en fuentes de energía no convencional. L.1715/2014, art. 11." },
  { format_code: '1011', code: '8275', name: "Deducción por depreciación de maquinarias, equipos y obras civiles de proyectos de fuentes de energía no convencionales. Art. 14 L. 1715/2014" },
  { format_code: '1011', code: '8276', name: "Costos y deducciones fiscales no reconocidas contablemente (diferencias temporarias), E.T., art. 59 y 105, num.1." },
  { format_code: '1011', code: '8277', name: "Deducciones por atenciones a clientes, proveedores y trabajadores. E.T., art. 107-1, inciso 1." },
  { format_code: '1011', code: '8278', name: "Deducciones por pagos salariales y prestacionales, provenientes de litigios. E.T., art. 107-1, inciso 2." },
  { format_code: '1011', code: '8279', name: "Deducción de cesantías consolidadas. E.T., art.110. No debe contener los valores especificados en otros conceptos." },
  { format_code: '1011', code: '8282', name: "Pagos a jurisdicciones no cooperantes, de baja o nula imposición y a entidades con regímenes preferentes. E.T., art. 124-2" },
  { format_code: '1011', code: '8283', name: "Deducción por depreciación. E.T., art. 128." },
  { format_code: '1011', code: '8284', name: "Costo por depreciación" },
  { format_code: '1011', code: '8285', name: "Costo o deducción por obsolescencia. E.T., art. 129" },
  { format_code: '1011', code: '8286', name: "Deducción de inversiones. E.T., art. 142" },
  { format_code: '1011', code: '8287', name: "Deducción por amortización de activos intangibles. E.T., Art. 143 del E.T. (Modificado por el artículo 85 de la Ley 1819 de 2016)" },
  { format_code: '1011', code: '8288', name: "Amortización inversiones en exploración, desarrollo y construcción de minas, y yacimientos de petróleo y gas. E.T., art. 143-1, modificado L. 1819/2016, art. 86" },
  { format_code: '1011', code: '8290', name: "Pérdidas sufridas en actividades agropecuarias. E.T., art. 150" },
  { format_code: '1011', code: '8292', name: "Deducción por inversiones en evaluación y exploración de recursos naturales no renovables. E.T., Art.159, modificado L. 1819/2016, art. 92." },
  { format_code: '1011', code: '8293', name: "Deducción por agotamiento en explotación de minas, gases distintos de hidrocarburos y depósitos naturales. E.T., art. 167" },
  { format_code: '1011', code: '8294', name: "Deducción por pago impuesto al carbono, como mayor valor del costo del bien. L. 1819/2016, Art. 222, parágrafo 2. Sujeto pasivo del impuesto" },
  { format_code: '1011', code: '8295', name: "Deducción por pagos efectuados a las empresas promotoras de salud EPS y los aportes al Sistema de Riesgos Laborales." },
  { format_code: '1011', code: '8296', name: "Deducciones por contribución a educación destinados a programas de becas de estudios totales o parciales. E.T., art. 107-2 literal a)" },
  { format_code: '1011', code: '8297', name: "Deducciones por contribución a educación destinados a programas o centros de atención, estimulación y desarrollo integral. E.T., art. 107-2 literal b)" },
  { format_code: '1011', code: '8298', name: "Deducciones por contribución a educación por aportes a instituciones de educación básica-primaria y secundaria y media reconocidas por el Ministerio de Educación y educación técnica, tecnológica y educación superior. E.T., art. 107-2 literal c)" },
  { format_code: '1011', code: '8299', name: "Deducciones de otros pagos a casas matrices o sucursales 124-1 E.T." },
  { format_code: '1011', code: '8400', name: "Deducción del 120% de los pagos que el empleador realice por concepto de salario, en relación con los empleados que sean menores de veintiocho (28) años, siempre y cuando se trate del primer empleo de la persona. E.T., art. 108-5, adicionado L. 2010 de 2019, art. 88." },
  { format_code: '1011', code: '8401', name: "Deducción de las instituciones prestadoras de salud (IPS) contribuyentes por la cartera, reconocida y certificada por el liquidador, correspondiente a los patrimonios de las Entidades Promotoras de Salud (EPS) que se encuentren en medida de intervención forzosa administrativa para liquidar por parte de la Superintendencia Nacional de Salud. L. 2010 de 2019, art. 97." },
  { format_code: '1011', code: '8402', name: "Deducción por inversiones o donaciones en proyectos de economía creativa del artículo 195 de la Ley 1607 de 2012 (adicionado por la Ley 1955 de 2019 Art. 180)." },
  { format_code: '1011', code: '8403', name: "Deducción por donaciones realizadas por entidades del régimen tributario especial parágrafo 1 del artículo 357 del estatuto Tributario." },
  { format_code: '1011', code: '8405', name: "Deducción por deterioro (provisión individual) de cartera de dudoso o difícil cobro. E.T.,art.145, DUR 1625 de 2016 arts.1.2.1.18.19 y 1.2.1.18.20." },
  { format_code: '1011', code: '8406', name: "Deducción por deterioro (provisión general) de cartera de dudoso o difícil cobro. E.T.,art.145, DUR 1625 de 2016 art.1.2.1.18.21." },
  { format_code: '1011', code: '8407', name: "Deducción por inversiones realizadas en investigación, desarrollo tecnológico e innovación. E.T., art.158-1, inc. 1" },
  { format_code: '1011', code: '8412', name: "Depreciación especial aplicada por contribuyentes del régimen de Mega-inversiones que realicen nuevas inversiones. E.T. art.235-3, num.2." },
  { format_code: '1011', code: '8413', name: "Deducción por provisiones de cartera hipotecaria de dudoso o difícil cobro. DUR 1625 de 2016 art.1.2.1.18.26." },
  { format_code: '1011', code: '8414', name: "Deducción deterioro de cartera de Entidades Promotoras de Salud -EPS en liquidación forzosa intervenidas por la Superintendencia Nacional de Salud. L. 1819/2016, art.375,modificado por L. 2010/ 2019, art.97" },
  { format_code: '1011', code: '8415', name: "Deducción deterioro de cartera de dudoso o difícil cobro E.T. art. 145. Par. 1." },
  { format_code: '1011', code: '8421', name: "Deducción por pérdida en Ia enajenación de activos. E.T., art. 149" },
  { format_code: '1011', code: '8422', name: "Deducción por pérdida en Ia enajenación de plusvalía. E.T., art. 154." },
  { format_code: '1011', code: '8423', name: "Deducción por perdida en la enajenación de bonos para la seguridad art 4 L 345/1996 derogado por el art 96 L 2277/2022" },
  { format_code: '1011', code: '8424', name: "Deducción por perdida en la enajenación de bonos para la seguridad para la paz art 5 L 487/1998 derogado por el art 96 L 2277/2022" },
  { format_code: '1011', code: '8425', name: "Deducción del 120% de salarios y prestaciones sociales por contratación de adulto mayor sin pensión L 2040/2020 art 2." },
  { format_code: '1011', code: '9001', name: "Exclusión de IVA por venta de materias primas químicas con destinación específica. E.T., art. 424, num. 1." },
  { format_code: '1011', code: '9002', name: "Exclusión de IVA por venta de materias primas destinadas a la producción de vacunas. Num 2 Art. 424 E.T." },
  { format_code: '1011', code: '9003', name: "Exclusión de IVA por venta de computadores personales. E.T., art. 424, num. 3, modificado L.1819/2016, art.175, num. 5." },
  { format_code: '1011', code: '9004', name: "Exclusión de IVA por venta de anticonceptivos femeninos. E.T., art.424, num.4." },
  { format_code: '1011', code: '9007', name: "Exclusión de IVA por venta de equipos, entre otros, para construcción, instalación, montaje y operación de sistemas de control y monitoreo ambiental. E.T., art. 424, num. 7." },
  { format_code: '1011', code: '9008', name: "Exclusión de IVA por venta de dispositivos móviles inteligentes. E.T., art. 424, num.6." },
  { format_code: '1011', code: '9009', name: "Exclusión de IVA por donaciones de alimentos de consumo humano a Bancos de Alimentos. E.T., art. 424, num.9" },
  { format_code: '1011', code: '9012', name: "Exclusiones de IVA por venta de objetos con interés artístico, cultural e histórico. E.T., art. 424, num. 13, modificado L. 1819/2016, art. 175, num. 11" },
  { format_code: '1011', code: '9013', name: "Exclusiones de IVA por venta de combustible para aviación para el servicio de transporte aéreo nacional con origen y destino a Guainía, Amazonas, Vaupés, San Andrés Islas y Providencia, Arauca y Vichada. E.T., art. 424, num 14" },
  { format_code: '1011', code: '9014', name: "Exclusiones de IVA en la venta de pólizas de seguros de carácter individual. E.T., art. 427. E.T." },
  { format_code: '1011', code: '9015', name: "Exclusión de IVA en la venta de equipos, entre otros, para fuentes de energía no convencionales. Art. 12 Ley 1715 de 2014." },
  { format_code: '1011', code: '9016', name: "Exclusión de IVA por venta de servicios médicos odontológicos, entre otros. E.T., art. 476, num. 1.  Art. 476 E.T." },
  { format_code: '1011', code: '9017', name: "Exclusión de IVA por venta de servicios de transporte. E.T., art. 476, num. 9." },
  { format_code: '1011', code: '9018', name: "Exclusión en IVA en intereses y rendimientos financieros por operaciones de crédito, E.T., art. 476, num. 16." },
  { format_code: '1011', code: '9019', name: "Exclusión de IVA en venta de servicios públicos. E.T., art. 476, numerales 11, 12, 13." },
  { format_code: '1011', code: '9020', name: "Exclusión de IVA en venta de servicio de arrendamiento. E.T., art. 476, num. 15." },
  { format_code: '1011', code: '9021', name: "Exclusión de IVA en venta de servicios de educación. E.T., art. 476, num.5" },
  { format_code: '1011', code: '9023', name: "Exclusión de IVA en venta de planes obligatorios de salud, ahorro individual, riesgos laborales y servicios de seguros y reaseguros. E.T., art. 476, num. 3." },
  { format_code: '1011', code: '9025', name: "Exclusión de IVA en servicios de promoción y fomento deportivo. E.T., art. 476, num.  29." },
  { format_code: '1011', code: '9026', name: "Exclusión de IVA en cine, en eventos y espectáculos. E.T., art. 476, num. 18, modificado por L 2277/2022 art 76." },
  { format_code: '1011', code: '9027', name: "Exclusión de IVA en venta de servicios de adecuación de tierras, producción agropecuaria y pesquera. E.T., art. 476, num. 24, modificado por L 2277/2022 art 76." },
  { format_code: '1011', code: '9028', name: "Exclusión de IVA comisiones pagadas en procesos de titularización de activos. E.T., art. 476, num. 22" },
  { format_code: '1011', code: '9029', name: "Exclusión de IVA en servicios funerarios, cremación, inhumación y exhumación E.T., art. 476, num. 19." },
  { format_code: '1011', code: '9030', name: "Exclusión de IVA en servicios de conexión y acceso a Internet estrato 3. E.T., art. 476, num 7." },
  { format_code: '1011', code: '9031', name: "Exclusión de IVA en comisiones por intermediación por la colocación de los planes de salud del sistema general de seguridad social. E.T., art. 476, num. 4" },
  { format_code: '1011', code: '9032', name: "Exclusión de IVA en comisiones percibidas por utilización de tarjetas crédito y débito. E.T., art. 476, num. 28" },
  { format_code: '1011', code: '9033', name: "Exclusión de IVA en servicios de alimentación contratados con recursos públicos y destinados al sistema penitenciario, de asistencia social y escuelas de educación pública. E.T., art. 476, num. 14." },
  { format_code: '1011', code: '9034', name: "Exclusión de IVA en servicios de transporte aéreo nacional donde no exista transporte terrestre organizado y hacia los demás destinos contemplados. E.T., art. 476, num. 10." },
  { format_code: '1011', code: '9035', name: "Exclusión de IVA en publicidad a través de periódicos y medios regionales. E.T., art. 476, num. 31" },
  { format_code: '1011', code: '9036', name: "Exclusión de IVA en la venta de productos de soporte nutricional del régimen especial. E.T., art. 424, num. 3, adicionado por L. 1819/2016 art. 175" },
  { format_code: '1011', code: '9037', name: "Exclusión de IVA en la venta de alimentos para propósitos médicos especiales para pacientes que requieren nutrición enteral. E.T., art. 424, num. 3, adicionado por L. 1819/2016 art. 175" },
  { format_code: '1011', code: '9038', name: "Exclusión de IVA en el territorio intendencia de San Andrés y Providencia. E.T., art. 423." },
  { format_code: '1011', code: '9039', name: "Exclusión de IVA en la venta de alimentos de consumo humano y animales importados de países colindantes de Vichada, Guajira, Guainía y Vaupés, destinados a consumo local en el departamento. E.T., art. 424, num. 8, modificado L. 1819/2016, art. 175, num. 8" },
  { format_code: '1011', code: '9041', name: "Exclusión de IVA en compraventa de maquinaria y equipos registrados en el registro nacional de reducción de emisiones de gases efecto invernadero. E.T., art. 424, num. 16, adicionado L. 1819/2016, art. 175, num. 16." },
  { format_code: '1011', code: '9042', name: "Exclusión de IVA en el petróleo crudo recibido por la Agencia Nacional de Hidrocarburos por regalías para su respectiva monetización. E.T., art. 424, parágrafo, adicionado L. 1819/2016, art. 175." },
  { format_code: '1011', code: '9043', name: "Exclusión de IVA en los servicios de educación virtual para el desarrollo de contenidos digitales. E.T., art. 476, num. 6, adicionado por L. 1819/2016 art. 187." },
  { format_code: '1011', code: '9044', name: "Exclusión de IVA en suministro de páginas web, servidores, computadora en la nube y mantenimiento a distancia. E.T., art. 476, num. 21, adicionado por L. 1819/2016 art. 187." },
  { format_code: '1011', code: '9045', name: "Exclusión de IVA en adquisición de licencias de software para el desarrollo comercial de contenidos digitales. E.T., art. 476, num. 20, adicionado por L. 1819/2016 art. 187." },
  { format_code: '1011', code: '9046', name: "Exclusión de IVA en servicios de reparación y mantenimiento de naves y artefactos marítimos y fluviales. E.T., art. 476, num. 30, adicionado por L. 1819/2016 art. 187." },
  { format_code: '1011', code: '9047', name: "Exclusión de IVA por servicios de hotelería y turismo prestados en zonas del régimen aduanero especial de Urabá, Tumaco, Guapi, Inírida, Puerto Carreño, La Primavera y Cumaribo, Maicao, Uribía y Manaure. E.T., art. 476, num. 26" },
  { format_code: '1011', code: '9048', name: "Exclusión de IVA por operaciones cambiarias de compra y venta de divisas. E.T., art. 476, num. 27" },
  { format_code: '1011', code: '9049', name: "Exclusión de IVA por servicios de intermediación para el pago de incentivos o transferencias monetarias condicionadas en el marco de los programas sociales. E.T., art. 476, num. 17" },
  { format_code: '1011', code: '9051', name: "Exclusión de IVA en la venta de alimentos consumo humano o animal, destinados a los departamentos de Amazonas, Guainía y Vaupés. E.T., art. 424, num. 13, adicionado L 1819/2016, art. 175, num. 13." },
  { format_code: '1011', code: '9052', name: "Exclusión de IVA en la venta de elementos de aseo, destinados a los departamentos de Amazonas, Guainía y Vaupés. E.T., art. 424, num. 13, adicionado L 1819/2016, art. 175, num. 13." },
  { format_code: '1011', code: '9053', name: "Exclusión de IVA en la venta de vestuario, destinado a los departamentos de Amazonas, Guainía y Vaupés. E.T., art. 424, num. 13, adicionado L 1819/2016, art. 175, num. 13." },
  { format_code: '1011', code: '9054', name: "Exclusión de IVA en la venta de medicamentos de uso humano y veterinario, destinados a los departamentos de Amazonas, Guainía y Vaupés. E.T., art. 424, num. 13, adicionado L 1819/2016, art. 175, num. 13" },
  { format_code: '1011', code: '9055', name: "Exclusión de IVA en la venta de materiales de construcción destinados a los departamentos de Amazonas, Guainía y Vaupés. E.T., art. 424, num. 13, adicionado L 1819/2016, art. 175, num. 13." },
  { format_code: '1011', code: '9056', name: "Exclusión de IVA en la venta de bicicletas, bicicletas eléctricas, motos eléctricas, patines, monopatines, monopatines eléctricos, patinetas, y patinetas eléctricas, de hasta 50 UVT. E.T., art. 424, num 17." },
  { format_code: '1011', code: '9057', name: "Exclusión de IVA en la venta de bienes facturados por los comerciantes definidos en el parágrafo 2 del artículo 34 de la Ley 98 de 1993. E.T., art. 424, num 18" },
  { format_code: '1011', code: '9058', name: "Exclusión de IVA en la venta de productos comprados o introducidos al Amazonas en el marco del convenio Colombo-Peruano y el convenio con la República Federativa del Brasil. E.T., art. 424, num 15" },
  { format_code: '1011', code: '9059', name: "Exclusión de IVA en servicios de administración de fondos del Estado y los servicios vinculados con la seguridad social de acuerdo con lo previsto en la Ley 100 de 1993, E.T., art. 476, num. 2" },
  { format_code: '1011', code: '9060', name: "Exclusión de IVA, primeros trescientos veinticinco (325) minutos mensuales del servicio telefónico local facturado a los usuarios estratos 1, 2 y 3 y servicio prestado desde teléfonos públicos, E.T., art. 476, num. 8" },
  { format_code: '1011', code: '9061', name: "Exclusión de IVA en comisiones percibidas por la administración de fondos de inversión colectiva, E.T., art. 476, num. 23." },
  { format_code: '1011', code: '9062', name: "Exclusión de IVA en servicios de corretaje de contratos de reaseguros, E.T., art. 476, num.32" },
  { format_code: '1011', code: '9065', name: "Exclusión de IVA en los servicios prestados a la ONU y a las entidades multilaterales de crédito, de acuerdo con los convenios ratificados por Colombia. Reglamentación Dec. 2076/1992, art. 21" },
  { format_code: '1011', code: '9066', name: "Exclusión de IVA en venta de chatarra de las subpartidas 72.04, 74.04 y 76.02. cuando no intervenga como enajenante o adquiriente una siderúrgica. Art.437-4 E.T., Art.1.3.2.1.9. Decreto 1625 de 2016" },
  { format_code: '1011', code: '9067', name: "Exclusión del IVA por la venta de bienes de diferentes partidas arancelarias que inician con la partida 01.03 y termina con la subpartida 96.09.10.00.00, contempladas en el inciso 1 del art. 424 E.T." },
  { format_code: '1011', code: '9069', name: "Exclusión de IVA por venta de bienes inmuebles numeral 12 Artículo 424 E.T" },
  { format_code: '1011', code: '9070', name: "Exclusión de IVA en comercialización de animales vivos, excepto los animales domésticos de compañía. ET art 476 núm. 25 modificado ley 2277/2020 art 76, art. 1" },
  { format_code: '1011', code: '9072', name: "Exclusión de IVA en el servicio de faenamiento ET art 476 núm. 25 A" },
  { format_code: '1011', code: '9100', name: "Tarifa del 5% venta de servicios de almacenamiento y comisiones productos agrícolas. E.T., art. 468-3, num. 1," },
  { format_code: '1011', code: '9101', name: "Tarifa del 5% por venta de seguro agropecuario. E.T., art. 468-3, num. 2." },
  { format_code: '1011', code: '9102', name: "Tarifa del 5% por venta de servicios prestados mediante entidades del Num. 1 Art. 19 E.T., con discapacidad. E.T., art. 468-3, num. 4, modificado por L. 1819/2016, art. 186." },
  { format_code: '1011', code: '9103', name: "Tarifa de 5% en venta de servicios de medicina prepagada y pólizas relacionadas. E.T., art. 468-3, num. 3," },
  { format_code: '1011', code: '9105', name: "Tarifa del 5% en venta de bienes sujetos a participación o impuesto al consumo de licores, vinos, aperitivos y similares del art. 202 L. 223/1995. E.T., art. 468-1, num. 2, adicionado L. 1819/2016, art. 185, num. 2." },
  { format_code: '1011', code: '9106', name: "Tarifa del 5% en las neveras nuevas para sustitución, sujetas al reglamento técnico de etiquetado (RETIQ). E.T., art. 468-1, num. 3, adicionado L. 1819/2016, art. 185, num.3." },
  { format_code: '1011', code: '9107', name: "Tarifa del 5%.  El ingreso al productor en la venta de Gasolina y ACPM. E.T. Numeral 4 art. 468-1 del Art. 174 Ley 1955 de 2019." },
  { format_code: '1011', code: '9110', name: "Tarifa del 5% en la venta de bienes de las partidas que inician desde la 09.01. y termina en la partida 90.32., contemplados en el inciso 1 del artículo 468-1 E.T.." },
  { format_code: '1011', code: '9200', name: "Exención de IVA en venta de alcohol carburante. E.T., art. 477, num. 1." },
  { format_code: '1011', code: '9202', name: "Exención de IVA venta de libros y revistas de carácter científico y cultural. E.T., art. 478." },
  { format_code: '1011', code: '9203', name: "Exención de IVA por prestación servicios en el país utilizados en el exterior. E.T., art. 481, lit. c." },
  { format_code: '1011', code: '9204', name: "Exención de IVA por prestación de servicios turísticos a extranjeros en el territorio colombiano. E.T., art. 481, lit. d." },
  { format_code: '1011', code: '9205', name: "Exención de IVA por cuadernos subpartida 48.20.20.00.00, diarios, publicaciones periódicas, impresos, demás subpartida 49.02. E.T., art. 481, lit. f." },
  { format_code: '1011', code: '9206', name: "Exención de IVA por servicio de conexión estrato 1 y 2. E.T., art. 481, lit. h." },
  { format_code: '1011', code: '9207', name: "Exención de IVA en venta de municiones y material de guerra y elementos pertenecientes a Fuerzas Militares y Policía Nacional. E.T., art. 477, num. 3." },
  { format_code: '1011', code: '9208', name: "Exención de IVA en la venta de vehículos automotores de transporte público de pasajeros completos y el chasis con motor y la carrocería adquiridos individualmente para conformar un vehículo automotor completo nuevo, de transporte público de pasajeros. E.T., art. 477, num. 4" },
  { format_code: '1011', code: '9209', name: "Exención de IVA en la venta de vehículos automotores de servicio público o particular, de transporte de carga completos y el chasis con motor y la carrocería adquiridos individualmente para conformar un vehículo automotor completo nuevo de transporte de carga de más de 10.5 toneladas de peso bruto vehicular. E.T., art. 477, num. 5.." },
  { format_code: '1011', code: '9210', name: "Exención en IVA en la venta de bicicletas y sus partes; motocicletas y sus partes y motocarros y sus partes, que se introduzcan y comercialicen en los departamentos de Amazonas, Guainía, Guaviare, Vaupés y Vichada, siempre y cuando se destinen exclusivamente al consumo dentro del mismo departamento. Numeral 6 del art. 477 del E.T.." },
  { format_code: '1011', code: '9211', name: "Exención de IVA en la venta de alimentos consumo humano o animal que se introduzcan y comercialicen al departamento de Amazonas E.T., art. 477, num. 7, adicionado por el art. 12 de la Ley 2010 de 2019" },
  { format_code: '1011', code: '9212', name: "Exención de IVA en la venta de elementos de aseo que se introduzcan y comercialicen al departamento de Amazonas. E.T., art. 477, num. 7, adicionado por el art. 12 de la Ley 2010 de 2019" },
  { format_code: '1011', code: '9213', name: "Exención de IVA en la venta de vestuario, que se introduzcan y comercialicen al departamento de Amazonas. E.T., art. 477, num. 7, adicionado por el art. 12 de la Ley 2010 de 2019" },
  { format_code: '1011', code: '9214', name: "Exención de IVA en la venta de medicamentos de uso humano y veterinario, que se introduzcan y comercialicen al departamento de Amazonas E.T., art. 477, num. 7, adicionado por el art. 12 de la Ley 2010 de 2019" },
  { format_code: '1011', code: '9215', name: "Exención de IVA en la venta de materiales de construcción que se introduzcan y comercialicen al departamento de Amazonas. E.T., art. 477, num. 7, adicionado por el art. 12 de la Ley 2010 de 2019" },
  { format_code: '1011', code: '9216', name: "Exención por prestación de servicios turísticos a extranjeros en el territorio colombiano. E.T., art. 481, lit. d, inc. 2" },
  { format_code: '1011', code: '9217', name: "Exención de IVA en la venta de bienes que inician desde la partida 01.02, y termina en la partida 96.19.  contemplados en el inciso 1 del artículo 477 del E.T. y Sentencia C117 de 2018." },
  { format_code: '1011', code: '9218', name: "Exención de IVA por uso de recursos de auxilios o donaciones de entidades o gobiernos extranjeros convenidos con el Gobierno colombiano, destinados a realizar programas de utilidad común y registrados en la Agencia Presidencial de la Cooperación Internacional. L. 788/2002, art. 96, modificado por el art. 38 de la Ley 2010 de 2019." },
  { format_code: '1011', code: '9221', name: "Exención de IVA en compra o donación de vehículos, equipos o elementos nuevos o usados utilizados para la gestión integral del riesgo, preparativos y atención de rescate a la actividad bomberil y la atención de incidentes con materiales peligrosos. L.1575/2012, art. 32, modificado por L.2010/2019, art. 32" },
  { format_code: '1011', code: '9222', name: "Exención de IVA por exportación de servicios relacionados con la producción de obra de cine, televisión, audiovisuales de cualquier género y con el desarrollo de software. Parágrafo del Art. 481 del E.T." },
  { format_code: '1009', code: '2201', name: "Saldo de los pasivos con proveedores" },
  { format_code: '1009', code: '2202', name: "Saldo de los pasivos con compañías vinculadas accionistas y socios" },
  { format_code: '1009', code: '2203', name: "Saldo de las obligaciones financieras" },
  { format_code: '1009', code: '2204', name: "Saldo de los pasivos por impuestos, gravámenes y tasas" },
  { format_code: '1009', code: '2206', name: "Saldo de los demás pasivos," },
  { format_code: '1009', code: '2207', name: "Saldo del Pasivo determinado por el cálculo Actuarial, con el NIT del informante" },
  { format_code: '1009', code: '2208', name: "Pasivos respaldados en documento de fecha cierta" },
  { format_code: '1009', code: '2209', name: "Pasivos exclusivos de las compañías de seguros" },
  { format_code: '1009', code: '2211', name: "Valor de los pasivos por depósitos judiciales. Se debe identicar al beneficiario" },
  { format_code: '1009', code: '2212', name: "valor del pasivo por ingresos diferidos por puntos premio otorgados en programas de fidelización" },
  { format_code: '1009', code: '2213', name: "valor del pasivo por ingresos diferidos contemplados en el art. 23-1 del E.T.," },
  { format_code: '1009', code: '2214', name: "Saldo de los pasivos por aportes parafiscales, salud, pensión y cesantías." },
  { format_code: '1009', code: '2215', name: "Saldo de los pasivos laborales consolidados en cabeza del trabajador, sin incluir cesantías." },
  { format_code: '1009', code: '2216', name: "El valor de saldo de los pasivos de entidades financieras donde no sea posible identificar al acreedor nacional. Se debe reportar con el NIT de la entidad informante." },
  { format_code: '1009', code: '2217', name: "El valor de saldo de los pasivos de entidades financieras donde no sea posible identificar al acreedor del exterior. Se debe reportar con el NIT de la entidad informante." },
];
