/**
 * Métodos de Pago - Datos DIAN
 * El id del viejo sistema no aplica, se usa code como id
 */
export const paymentMethods = [
  { id: '1', code: '1', name: 'Instrumento no definido' },
  { id: '2', code: '2', name: 'Crédito ACH' },
  { id: '3', code: '3', name: 'Débito ACH' },
  { id: '4', code: '4', name: 'Reversión débito de demanda ACH' },
  { id: '5', code: '5', name: 'Reversión crédito de demanda ACH' },
  { id: '6', code: '6', name: 'Crédito de demanda ACH' },
  { id: '7', code: '7', name: 'Débito de demanda ACH' },
  { id: '8', code: '8', name: 'Mantener' },
  { id: '9', code: '9', name: 'Clearing Nacional o Regional' },
  { id: '10', code: '10', name: 'Efectivo' },
  { id: '11', code: '11', name: 'Reversión Crédito Ahorro' },
  { id: '12', code: '12', name: 'Reversión Débito Ahorro' },
  { id: '13', code: '13', name: 'Crédito Ahorro' },
  { id: '14', code: '14', name: 'Débito Ahorro' },
  { id: '15', code: '15', name: 'Bookentry Crédito' },
  { id: '16', code: '16', name: 'Bookentry Débito' },
  { id: '17', code: '17', name: 'Concentración de la demanda en efectivo /Desembolso Crédito (CCD)' },
  { id: '18', code: '18', name: 'Concentración de la demanda en efectivo / Desembolso (CCD) débito' },
  { id: '19', code: '19', name: 'Crédito Pago negocio corporativo (CTP)' },
  { id: '20', code: '20', name: 'Cheque' },
  { id: '21', code: '21', name: 'Poyecto bancario' },
  { id: '22', code: '22', name: 'Proyecto bancario certificado' },
  { id: '23', code: '23', name: 'Cheque bancario' },
  { id: '24', code: '24', name: 'Nota cambiaria esperando aceptación' },
  { id: '25', code: '25', name: 'Cheque certificado' },
  { id: '26', code: '26', name: 'Cheque Local' },
  { id: '27', code: '27', name: 'Débito Pago Neogcio Corporativo (CTP)' },
  { id: '28', code: '28', name: 'Crédito Negocio Intercambio Corporativo (CTX)' },
  { id: '29', code: '29', name: 'Débito Negocio Intercambio Corporativo (CTX)' },
  { id: '30', code: '30', name: 'Transferecia Crédito' },
  { id: '31', code: '31', name: 'Transferencia Débito' },
  { id: '32', code: '32', name: 'Concentración Efectivo / Desembolso Crédito plus (CCD+)' },
  { id: '33', code: '33', name: 'Concentración Efectivo / Desembolso Débito plus (CCD+)' },
  { id: '34', code: '34', name: 'Pago y depósito pre acordado (PPD)' },
  { id: '35', code: '35', name: 'Concentración efectivo ahorros / Desembolso Crédito (CCD)' },
  { id: '36', code: '36', name: 'Concentración efectivo ahorros / Desembolso Débito (CCD)' },
  { id: '37', code: '37', name: 'Pago Negocio Corporativo Ahorros Crédito (CTP)' },
  { id: '38', code: '38', name: 'Pago Negocio Corporativo Ahorros Débito (CTP)' },
  { id: '39', code: '39', name: 'Crédito Negocio Intercambio Corporativo (CTX)' },
  { id: '40', code: '40', name: 'Débito Negocio Intercambio Corporativo (CTX)' },
  { id: '41', code: '41', name: 'Concentración efectivo/Desembolso Crédito plus (CCD+)' },
  { id: '42', code: '42', name: 'Consignación bancaria' },
  { id: '43', code: '43', name: 'Concentración efectivo / Desembolso Débito plus (CCD+)' },
  { id: '44', code: '44', name: 'Nota cambiaria' },
  { id: '45', code: '45', name: 'Transferencia Crédito Bancario' },
  { id: '46', code: '46', name: 'Transferencia Débito Interbancario' },
  { id: '47', code: '47', name: 'Transferencia Débito Bancaria' },
  { id: '48', code: '48', name: 'Tarjeta Crédito' },
  { id: '49', code: '49', name: 'Tarjeta Débito' },
  { id: '50', code: '50', name: 'Postgiro' },
  { id: '51', code: '51', name: 'Telex estándar bancario francés' },
  { id: '52', code: '52', name: 'Pago comercial urgente' },
  { id: '53', code: '53', name: 'Pago Tesorería Urgente' },
  { id: '54', code: '60', name: 'Nota promisoria' },
  { id: '55', code: '61', name: 'Nota promisoria firmada por el acreedor' },
  { id: '56', code: '62', name: 'Nota promisoria firmada por el acreedor, avalada por el banco' },
  { id: '57', code: '63', name: 'Nota promisoria firmada por el acreedor, avalada por un tercero' },
  { id: '58', code: '64', name: 'Nota promisoria firmada por el banco' },
  { id: '59', code: '65', name: 'Nota promisoria firmada por un banco avalada por otro banco' },
  { id: '60', code: '66', name: 'Nota promisoria firmada' },
  { id: '61', code: '67', name: 'Nota promisoria firmada por un tercero avalada por un banco' },
  { id: '62', code: '70', name: 'Retiro de nota por el acreedor' },
  { id: '63', code: '74', name: 'Retiro de nota por el acreedor sobre un banco' },
  { id: '64', code: '75', name: 'Retiro de nota por el acreedor, avalada por otro banco' },
  { id: '65', code: '76', name: 'Retiro de nota por el acreedor, sobre un banco avalada por un tercero' },
  { id: '66', code: '77', name: 'Retiro de una nota por el acreedor sobre un tercero' },
  { id: '67', code: '78', name: 'Retiro de una nota por el acreedor sobre un tercero avalada por un banco' },
  { id: '68', code: '91', name: 'Nota bancaria transferible' },
  { id: '69', code: '92', name: 'Cheque local transferible' },
  { id: '70', code: '93', name: 'Giro referenciado' },
  { id: '71', code: '94', name: 'Giro urgente' },
  { id: '72', code: '95', name: 'Giro formato abierto' },
  { id: '73', code: '96', name: 'Método de pago solicitado no usado' },
  { id: '74', code: '97', name: 'Clearing entre partners' },
  { id: '75', code: 'ZZZ', name: 'Acuerdo mutuo' },
];
