import { PrismaClient, AccountType } from '@prisma/client-master';

// Clases principales del PUC colombiano (1 dígito) - sin padre
const PUC_CLASSES = [
  { code: '1', name: 'Activo', type: AccountType.ASSET },
  { code: '2', name: 'Pasivo', type: AccountType.LIABILITY },
  { code: '3', name: 'Patrimonio', type: AccountType.EQUITY },
  { code: '4', name: 'Ingresos', type: AccountType.INCOME },
  { code: '5', name: 'Gasto', type: AccountType.EXPENSE },
  { code: '6', name: 'Costos de venta', type: AccountType.COST },
  { code: '7', name: 'Costos de Produccion', type: AccountType.PRODUCTION_COST },
  { code: '8', name: 'Cuentas de Orden Deudoras', type: AccountType.DEBTOR_ACCOUNTS },
  { code: '9', name: 'Cuentas de Orden Acreedoras', type: AccountType.CREDITOR_ACCOUNTS },
];

// Cuentas con padre (ordenadas por jerarquía)
const PUC_ACCOUNTS = [
  // Nivel 2 (2 dígitos)
  { code: '11', name: 'Efectivo y equivalentes de efectivo', type: AccountType.ASSET, parent_code: '1' },
  { code: '13', name: 'Deudores comerciales y otras cuentas por cobrar', type: AccountType.ASSET, parent_code: '1' },
  { code: '14', name: 'Inventarios', type: AccountType.ASSET, parent_code: '1' },
  { code: '15', name: 'Propiedad, Planta y Equipo', type: AccountType.ASSET, parent_code: '1' },
  { code: '22', name: 'Proveedores', type: AccountType.LIABILITY, parent_code: '2' },
  { code: '23', name: 'Acreedores comerciales y otras cuentas por pagar', type: AccountType.LIABILITY, parent_code: '2' },
  { code: '24', name: 'Pasivos por impuestos', type: AccountType.LIABILITY, parent_code: '2' },
  { code: '25', name: 'Beneficios a empleados', type: AccountType.LIABILITY, parent_code: '2' },
  { code: '27', name: 'Diferidos', type: AccountType.LIABILITY, parent_code: '2' },
  { code: '28', name: 'Pasivos no financieros', type: AccountType.LIABILITY, parent_code: '2' },
  { code: '31', name: 'Capital social', type: AccountType.EQUITY, parent_code: '3' },
  { code: '36', name: 'Resultado del ejercicio', type: AccountType.EQUITY, parent_code: '3' },
  { code: '37', name: 'Resultados de ejercicios anteriores', type: AccountType.EQUITY, parent_code: '3' },
  { code: '41', name: 'Ingresos operacionales', type: AccountType.INCOME, parent_code: '4' },
  { code: '42', name: 'Ingresos no operacionales', type: AccountType.INCOME, parent_code: '4' },
  { code: '51', name: 'Administrativos', type: AccountType.EXPENSE, parent_code: '5' },
  { code: '52', name: 'Gastos no Administrativos', type: AccountType.EXPENSE, parent_code: '5' },
  { code: '53', name: 'Gastos no operacionales', type: AccountType.EXPENSE, parent_code: '5' },
  { code: '61', name: 'Costo de ventas y de prestación de servicios', type: AccountType.COST, parent_code: '6' },
  // Nivel 4 (4 dígitos)
  { code: '1105', name: 'Caja', type: AccountType.ASSET, parent_code: '11' },
  { code: '1110', name: 'Bancos', type: AccountType.ASSET, parent_code: '11' },
  { code: '1305', name: 'Clientes nacionales', type: AccountType.ASSET, parent_code: '13' },
  { code: '1330', name: 'Anticipos y avances', type: AccountType.ASSET, parent_code: '13' },
  { code: '1355', name: 'Anticipo de impuestos y contribuciones o', type: AccountType.ASSET, parent_code: '13' },
  { code: '1435', name: 'Mercancías no fabricadas por la empresa', type: AccountType.ASSET, parent_code: '14' },
  { code: '1520', name: 'Maquinaria y equipo', type: AccountType.ASSET, parent_code: '15' },
  { code: '1592', name: 'Depreciacion acumulada', type: AccountType.ASSET, parent_code: '15' },
  { code: '2205', name: 'Proveedores nacionales', type: AccountType.LIABILITY, parent_code: '22' },
  { code: '2365', name: 'Retenciones en la fuente', type: AccountType.LIABILITY, parent_code: '23' },
  { code: '2367', name: 'Impuesto a las ventas retenido', type: AccountType.LIABILITY, parent_code: '23' },
  { code: '2368', name: 'Impuesto de industria y comercio retenido', type: AccountType.LIABILITY, parent_code: '23' },
  { code: '2370', name: 'Aportes a empresas promotoras de salud eps', type: AccountType.LIABILITY, parent_code: '23' },
  { code: '2380', name: 'Acreedores varios', type: AccountType.LIABILITY, parent_code: '23' },
  { code: '2408', name: 'Impuesto sobre las ventas por pagar', type: AccountType.LIABILITY, parent_code: '24' },
  { code: '2495', name: 'Otros', type: AccountType.LIABILITY, parent_code: '24' },
  { code: '2505', name: 'Salarios por pagar', type: AccountType.LIABILITY, parent_code: '25' },
  { code: '2705', name: 'Ingresos recibidos por anticipado', type: AccountType.LIABILITY, parent_code: '27' },
  { code: '2799', name: 'Cuenta 2799', type: AccountType.LIABILITY, parent_code: '27' },
  { code: '2805', name: 'Anticipos y avances recibidos', type: AccountType.LIABILITY, parent_code: '28' },
  { code: '3105', name: 'Capital suscrito y pagado', type: AccountType.EQUITY, parent_code: '31' },
  { code: '3605', name: 'Utilidad del ejercicio', type: AccountType.EQUITY, parent_code: '36' },
  { code: '3705', name: 'Resultados de ejercicios anteriores', type: AccountType.EQUITY, parent_code: '37' },
  { code: '4135', name: 'Comercio al por mayor y al detal', type: AccountType.INCOME, parent_code: '41' },
  { code: '4210', name: 'Financieros', type: AccountType.INCOME, parent_code: '42' },
  { code: '5105', name: 'Gastos de personal', type: AccountType.EXPENSE, parent_code: '51' },
  { code: '5106', name: 'Cuenta 5106', type: AccountType.EXPENSE, parent_code: '51' },
  { code: '5125', name: 'Contribuciones y afiliaciones', type: AccountType.EXPENSE, parent_code: '51' },
  { code: '5130', name: 'Seguros', type: AccountType.EXPENSE, parent_code: '51' },
  { code: '5155', name: 'Gastos de viaje', type: AccountType.EXPENSE, parent_code: '51' },
  { code: '5160', name: 'Depreciacion', type: AccountType.EXPENSE, parent_code: '51' },
  { code: '5199', name: 'Otros gastos', type: AccountType.EXPENSE, parent_code: '51' },
  { code: '5205', name: 'Gastos de personal', type: AccountType.EXPENSE, parent_code: '52' },
  { code: '5225', name: 'Contribuciones y afiliaciones', type: AccountType.EXPENSE, parent_code: '52' },
  { code: '5230', name: 'Seguros', type: AccountType.EXPENSE, parent_code: '52' },
  { code: '5295', name: 'Diversos', type: AccountType.EXPENSE, parent_code: '52' },
  { code: '5299', name: 'Otros gastos', type: AccountType.EXPENSE, parent_code: '52' },
  { code: '5305', name: 'Financieros', type: AccountType.EXPENSE, parent_code: '53' },
  { code: '6135', name: 'Comercio al por mayor y al por menor', type: AccountType.COST, parent_code: '61' },
  // Nivel 6 (6 dígitos)
  { code: '110505', name: 'Caja general', type: AccountType.ASSET, parent_code: '1105' },
  { code: '111005', name: 'Moneda nacional', type: AccountType.ASSET, parent_code: '1110' },
  { code: '130505', name: 'Clientes nacionales', type: AccountType.ASSET, parent_code: '1305' },
  { code: '133005', name: 'A proveedores', type: AccountType.ASSET, parent_code: '1330' },
  { code: '133015', name: 'A trabajadores', type: AccountType.ASSET, parent_code: '1330' },
  { code: '135515', name: 'Anticipo Retención en la fuente', type: AccountType.ASSET, parent_code: '1355' },
  { code: '135517', name: 'Impuesto a las ventas retenido', type: AccountType.ASSET, parent_code: '1355' },
  { code: '135518', name: 'Impuesto de industria y comercio retenido', type: AccountType.ASSET, parent_code: '1355' },
  { code: '135519', name: 'Iva a favor', type: AccountType.ASSET, parent_code: '1355' },
  { code: '143501', name: 'Mercancías', type: AccountType.ASSET, parent_code: '1435' },
  { code: '152005', name: 'Maquinaria y equipo de oficina', type: AccountType.ASSET, parent_code: '1520' },
  { code: '159205', name: 'Depreciacion acumulada de maquinaria y equipo', type: AccountType.ASSET, parent_code: '1592' },
  { code: '220505', name: 'Proveedores nacionales', type: AccountType.LIABILITY, parent_code: '2205' },
  { code: '236540', name: 'Retención por compras', type: AccountType.LIABILITY, parent_code: '2365' },
  { code: '236555', name: 'Retencion en la fuente por pagar', type: AccountType.LIABILITY, parent_code: '2365' },
  { code: '236701', name: 'Impuesto a las ventas retenido', type: AccountType.LIABILITY, parent_code: '2367' },
  { code: '236805', name: 'Retención industria y comercio Ica', type: AccountType.LIABILITY, parent_code: '2368' },
  { code: '237035', name: 'Aportes de salud por pagar', type: AccountType.LIABILITY, parent_code: '2370' },
  { code: '237040', name: 'Aportes de pension por pagar', type: AccountType.LIABILITY, parent_code: '2370' },
  { code: '237045', name: 'ICBF por pagar', type: AccountType.LIABILITY, parent_code: '2370' },
  { code: '237050', name: 'SENA por pagar', type: AccountType.LIABILITY, parent_code: '2370' },
  { code: '237055', name: 'ARL por pagar', type: AccountType.LIABILITY, parent_code: '2370' },
  { code: '237060', name: 'CCF por pagar', type: AccountType.LIABILITY, parent_code: '2370' },
  { code: '238001', name: 'Anticipos por cobrar', type: AccountType.LIABILITY, parent_code: '2380' },
  { code: '238004', name: 'Sanciones por pagar', type: AccountType.LIABILITY, parent_code: '2380' },
  { code: '238020', name: 'Pension voluntaria por pagar', type: AccountType.LIABILITY, parent_code: '2380' },
  { code: '238040', name: 'AFC por pagar', type: AccountType.LIABILITY, parent_code: '2380' },
  { code: '238050', name: 'Libranzas por pagar', type: AccountType.LIABILITY, parent_code: '2380' },
  { code: '238060', name: 'Cuotas sindicales por pagar', type: AccountType.LIABILITY, parent_code: '2380' },
  { code: '238065', name: 'Cooperativas por pagar', type: AccountType.LIABILITY, parent_code: '2380' },
  { code: '238070', name: 'Gravamenes por pagar', type: AccountType.LIABILITY, parent_code: '2380' },
  { code: '238075', name: 'Plan complementario por pagar', type: AccountType.LIABILITY, parent_code: '2380' },
  { code: '238080', name: 'Educacion por pagar', type: AccountType.LIABILITY, parent_code: '2380' },
  { code: '238085', name: 'Deudas del empleado por pagar', type: AccountType.LIABILITY, parent_code: '2380' },
  { code: '238090', name: 'Pagos a terceros por pagar', type: AccountType.LIABILITY, parent_code: '2380' },
  { code: '238098', name: 'Reintegros por pagar', type: AccountType.LIABILITY, parent_code: '2380' },
  { code: '238099', name: 'Otras deducciones por pagar', type: AccountType.LIABILITY, parent_code: '2380' },
  { code: '240805', name: 'Iva generado en ventas', type: AccountType.LIABILITY, parent_code: '2408' },
  { code: '240808', name: 'IVA por pagar', type: AccountType.LIABILITY, parent_code: '2408' },
  { code: '240810', name: 'Iva descontable por compras', type: AccountType.LIABILITY, parent_code: '2408' },
  { code: '249501', name: 'Impuesto al consumo nacional', type: AccountType.LIABILITY, parent_code: '2495' },
  { code: '249502', name: 'Impuesto bolsas', type: AccountType.LIABILITY, parent_code: '2495' },
  { code: '250505', name: 'Salarios por pagar', type: AccountType.LIABILITY, parent_code: '2505' },
  { code: '270505', name: 'Provision Cesantias', type: AccountType.LIABILITY, parent_code: '2705' },
  { code: '270515', name: 'Provision Vacaciones', type: AccountType.LIABILITY, parent_code: '2705' },
  { code: '279999', name: 'Otras provisiones', type: AccountType.LIABILITY, parent_code: '2799' },
  { code: '280505', name: 'De clientes', type: AccountType.LIABILITY, parent_code: '2805' },
  { code: '310505', name: 'Capital suscrito y pagado', type: AccountType.EQUITY, parent_code: '3105' },
  { code: '360505', name: 'Utilidad del ejercicio', type: AccountType.EQUITY, parent_code: '3605' },
  { code: '370505', name: 'Resultados de ejercicios anteriores', type: AccountType.EQUITY, parent_code: '3705' },
  { code: '413505', name: 'Comercio al por mayor y al detal', type: AccountType.INCOME, parent_code: '4135' },
  { code: '413506', name: 'Servicios', type: AccountType.INCOME, parent_code: '4135' },
  { code: '413507', name: 'Ingresos AIU Administracion', type: AccountType.INCOME, parent_code: '4135' },
  { code: '413508', name: 'Ingresos AIU Imprevistos', type: AccountType.INCOME, parent_code: '4135' },
  { code: '413509', name: 'Ingresos AIU Utilidad', type: AccountType.INCOME, parent_code: '4135' },
  { code: '510505', name: 'Gastos de personal', type: AccountType.EXPENSE, parent_code: '5105' },
  { code: '510514', name: 'Bonos EPCTV', type: AccountType.EXPENSE, parent_code: '5105' },
  { code: '510517', name: 'Anticipos', type: AccountType.EXPENSE, parent_code: '5105' },
  { code: '510529', name: 'Recargos dominicales/festivos', type: AccountType.EXPENSE, parent_code: '5105' },
  { code: '510574', name: 'Auxilio Alimentacion', type: AccountType.EXPENSE, parent_code: '5105' },
  { code: '510576', name: 'Bonificaciones', type: AccountType.EXPENSE, parent_code: '5105' },
  { code: '510582', name: 'Compensaciones', type: AccountType.EXPENSE, parent_code: '5105' },
  { code: '510587', name: 'Vacaciones compensadas', type: AccountType.EXPENSE, parent_code: '5105' },
  { code: '510589', name: 'Licencias remuneradas', type: AccountType.EXPENSE, parent_code: '5105' },
  { code: '510593', name: 'Licencias no remuneradas', type: AccountType.EXPENSE, parent_code: '5105' },
  { code: '510597', name: 'Licencia de maternidad', type: AccountType.EXPENSE, parent_code: '5105' },
  { code: '510599', name: 'Huelga legal', type: AccountType.EXPENSE, parent_code: '5105' },
  { code: '510600', name: 'Cesantias', type: AccountType.EXPENSE, parent_code: '5106' },
  { code: '512545', name: 'SENA', type: AccountType.EXPENSE, parent_code: '5125' },
  { code: '512560', name: 'Aporte Salud', type: AccountType.EXPENSE, parent_code: '5125' },
  { code: '512570', name: 'Bonificacion de retiro', type: AccountType.EXPENSE, parent_code: '5125' },
  { code: '512575', name: 'Teletrabajo', type: AccountType.EXPENSE, parent_code: '5125' },
  { code: '512580', name: 'Aporte Pension', type: AccountType.EXPENSE, parent_code: '5125' },
  { code: '512590', name: 'Horas extras diurnas', type: AccountType.EXPENSE, parent_code: '5125' },
  { code: '513005', name: 'ARL', type: AccountType.EXPENSE, parent_code: '5130' },
  { code: '513025', name: 'Comisiones', type: AccountType.EXPENSE, parent_code: '5130' },
  { code: '513030', name: 'Auxilios', type: AccountType.EXPENSE, parent_code: '5130' },
  { code: '513040', name: 'Dotacion', type: AccountType.EXPENSE, parent_code: '5130' },
  { code: '513045', name: 'Horas extras nocturnas', type: AccountType.EXPENSE, parent_code: '5130' },
  { code: '513050', name: 'Caja de Compensacion', type: AccountType.EXPENSE, parent_code: '5130' },
  { code: '513060', name: 'Prima de Servicios', type: AccountType.EXPENSE, parent_code: '5130' },
  { code: '513065', name: 'Auxilio de transporte', type: AccountType.EXPENSE, parent_code: '5130' },
  { code: '513075', name: 'Incapacidades', type: AccountType.EXPENSE, parent_code: '5130' },
  { code: '515505', name: 'Alojamiento y manutención', type: AccountType.EXPENSE, parent_code: '5155' },
  { code: '516005', name: 'Depreciacion de maquinaria y equipo', type: AccountType.EXPENSE, parent_code: '5160' },
  { code: '519900', name: 'Otros devengos', type: AccountType.EXPENSE, parent_code: '5199' },
  { code: '519901', name: 'Alimentos y bebidas', type: AccountType.EXPENSE, parent_code: '5199' },
  { code: '519902', name: 'Arriendo o vivienda', type: AccountType.EXPENSE, parent_code: '5199' },
  { code: '519903', name: 'Servicios publicos', type: AccountType.EXPENSE, parent_code: '5199' },
  { code: '519904', name: 'Transporte', type: AccountType.EXPENSE, parent_code: '5199' },
  { code: '519905', name: 'Salud', type: AccountType.EXPENSE, parent_code: '5199' },
  { code: '519906', name: 'Educacion', type: AccountType.EXPENSE, parent_code: '5199' },
  { code: '519907', name: 'Recreacion y cultura', type: AccountType.EXPENSE, parent_code: '5199' },
  { code: '519908', name: 'Comunicaciones', type: AccountType.EXPENSE, parent_code: '5199' },
  { code: '519909', name: 'Vestido y calzado', type: AccountType.EXPENSE, parent_code: '5199' },
  { code: '519910', name: 'Restaurantes y comidas fuera', type: AccountType.EXPENSE, parent_code: '5199' },
  { code: '519911', name: 'Muebles y mantenimiento del hogar', type: AccountType.EXPENSE, parent_code: '5199' },
  { code: '519912', name: 'Cuidado personal', type: AccountType.EXPENSE, parent_code: '5199' },
  { code: '519913', name: 'Seguros', type: AccountType.EXPENSE, parent_code: '5199' },
  { code: '519914', name: 'Impuestos', type: AccountType.EXPENSE, parent_code: '5199' },
  { code: '519915', name: 'Honorarios profesionales', type: AccountType.EXPENSE, parent_code: '5199' },
  { code: '519916', name: 'Contribuciones y afiliaciones', type: AccountType.EXPENSE, parent_code: '5199' },
  { code: '519920', name: 'Provisión Vacaciones - Operativo', type: AccountType.EXPENSE, parent_code: '5199' },
  { code: '519930', name: 'Provisión Cesantías - Operativo', type: AccountType.EXPENSE, parent_code: '5199' },
  { code: '519940', name: 'Provisión Prima - Operativo', type: AccountType.EXPENSE, parent_code: '5199' },
  { code: '519950', name: 'Provisión Intereses Cesantías - Operativo', type: AccountType.EXPENSE, parent_code: '5199' },
  // Cuentas 52 - Gastos no Administrativos (6 dígitos)
  { code: '520505', name: 'Gastos de personal - Administrativo', type: AccountType.EXPENSE, parent_code: '5205' },
  { code: '520513', name: 'Dotación - Administrativo', type: AccountType.EXPENSE, parent_code: '5205' },
  { code: '520514', name: 'Bonos EPCTV - Administrativo', type: AccountType.EXPENSE, parent_code: '5205' },
  { code: '520516', name: 'Bonos EPCTV - Administrativo', type: AccountType.EXPENSE, parent_code: '5205' },
  { code: '520517', name: 'Anticipos - Administrativo', type: AccountType.EXPENSE, parent_code: '5205' },
  { code: '520518', name: 'Anticipos - Administrativo', type: AccountType.EXPENSE, parent_code: '5205' },
  { code: '520526', name: 'Horas extras diurnas - Administrativo', type: AccountType.EXPENSE, parent_code: '5205' },
  { code: '520528', name: 'Horas extras nocturnas - Administrativo', type: AccountType.EXPENSE, parent_code: '5205' },
  { code: '520529', name: 'Recargos dominicales/festivos - Administrativo', type: AccountType.EXPENSE, parent_code: '5205' },
  { code: '520571', name: 'Incapacidades - Administrativo', type: AccountType.EXPENSE, parent_code: '5205' },
  { code: '520573', name: 'Teletrabajo - Administrativo', type: AccountType.EXPENSE, parent_code: '5205' },
  { code: '520574', name: 'Auxilio Alimentación - Administrativo', type: AccountType.EXPENSE, parent_code: '5205' },
  { code: '520576', name: 'Bonificaciones - Administrativo', type: AccountType.EXPENSE, parent_code: '5205' },
  { code: '520577', name: 'Bonificaciones - Administrativo', type: AccountType.EXPENSE, parent_code: '5205' },
  { code: '520579', name: 'Comisiones - Administrativo', type: AccountType.EXPENSE, parent_code: '5205' },
  { code: '520582', name: 'Compensaciones - Administrativo', type: AccountType.EXPENSE, parent_code: '5205' },
  { code: '520583', name: 'Compensaciones - Administrativo', type: AccountType.EXPENSE, parent_code: '5205' },
  { code: '520586', name: 'Bonificación de retiro - Administrativo', type: AccountType.EXPENSE, parent_code: '5205' },
  { code: '520587', name: 'Vacaciones compensadas - Administrativo', type: AccountType.EXPENSE, parent_code: '5205' },
  { code: '520588', name: 'Vacaciones compensadas - Administrativo', type: AccountType.EXPENSE, parent_code: '5205' },
  { code: '520589', name: 'Licencias remuneradas - Administrativo', type: AccountType.EXPENSE, parent_code: '5205' },
  { code: '520592', name: 'Licencias remuneradas - Administrativo', type: AccountType.EXPENSE, parent_code: '5205' },
  { code: '520593', name: 'Licencias no remuneradas - Administrativo', type: AccountType.EXPENSE, parent_code: '5205' },
  { code: '520594', name: 'Licencias no remuneradas - Administrativo', type: AccountType.EXPENSE, parent_code: '5205' },
  { code: '520596', name: 'Prima de Servicios - Administrativo', type: AccountType.EXPENSE, parent_code: '5205' },
  { code: '520597', name: 'Licencia de maternidad - Administrativo', type: AccountType.EXPENSE, parent_code: '5205' },
  { code: '520598', name: 'Licencia de maternidad - Administrativo', type: AccountType.EXPENSE, parent_code: '5205' },
  { code: '520599', name: 'Huelga legal - Administrativo', type: AccountType.EXPENSE, parent_code: '5205' },
  { code: '520600', name: 'Cesantías - Administrativo', type: AccountType.EXPENSE, parent_code: '5205' },
  { code: '520605', name: 'Cesantías - Administrativo', type: AccountType.EXPENSE, parent_code: '5205' },
  { code: '522540', name: 'ICBF - Administrativo', type: AccountType.EXPENSE, parent_code: '5225' },
  { code: '522545', name: 'SENA - Administrativo', type: AccountType.EXPENSE, parent_code: '5225' },
  { code: '522550', name: 'SENA - Administrativo', type: AccountType.EXPENSE, parent_code: '5225' },
  { code: '522555', name: 'Recargos dominicales/festivos - Administrativo', type: AccountType.EXPENSE, parent_code: '5225' },
  { code: '522560', name: 'Aporte Salud - Administrativo', type: AccountType.EXPENSE, parent_code: '5225' },
  { code: '522565', name: 'Aporte Salud - Administrativo', type: AccountType.EXPENSE, parent_code: '5225' },
  { code: '522570', name: 'Bonificación de retiro - Administrativo', type: AccountType.EXPENSE, parent_code: '5225' },
  { code: '522575', name: 'Teletrabajo - Administrativo', type: AccountType.EXPENSE, parent_code: '5225' },
  { code: '522580', name: 'Aporte Pensión - Administrativo', type: AccountType.EXPENSE, parent_code: '5225' },
  { code: '522585', name: 'Aporte Pensión - Administrativo', type: AccountType.EXPENSE, parent_code: '5225' },
  { code: '522590', name: 'Horas extras diurnas - Administrativo', type: AccountType.EXPENSE, parent_code: '5225' },
  { code: '522595', name: 'Recargos dominicales/festivos - Administrativo', type: AccountType.EXPENSE, parent_code: '5225' },
  { code: '523005', name: 'ARL - Administrativo', type: AccountType.EXPENSE, parent_code: '5230' },
  { code: '523010', name: 'ARL - Administrativo', type: AccountType.EXPENSE, parent_code: '5230' },
  { code: '523015', name: 'Auxilio Alimentación - Administrativo', type: AccountType.EXPENSE, parent_code: '5230' },
  { code: '523020', name: 'Huelga legal - Administrativo', type: AccountType.EXPENSE, parent_code: '5230' },
  { code: '523025', name: 'Comisiones - Administrativo', type: AccountType.EXPENSE, parent_code: '5230' },
  { code: '523030', name: 'Auxilios - Administrativo', type: AccountType.EXPENSE, parent_code: '5230' },
  { code: '523035', name: 'Auxilios - Administrativo', type: AccountType.EXPENSE, parent_code: '5230' },
  { code: '523040', name: 'Dotación - Administrativo', type: AccountType.EXPENSE, parent_code: '5230' },
  { code: '523045', name: 'Horas extras nocturnas - Administrativo', type: AccountType.EXPENSE, parent_code: '5230' },
  { code: '523050', name: 'Caja de Compensación - Administrativo', type: AccountType.EXPENSE, parent_code: '5230' },
  { code: '523055', name: 'Caja de Compensación - Administrativo', type: AccountType.EXPENSE, parent_code: '5230' },
  { code: '523060', name: 'Prima de Servicios - Administrativo', type: AccountType.EXPENSE, parent_code: '5230' },
  { code: '523065', name: 'Auxilio de transporte - Administrativo', type: AccountType.EXPENSE, parent_code: '5230' },
  { code: '523070', name: 'Auxilio de transporte - Administrativo', type: AccountType.EXPENSE, parent_code: '5230' },
  { code: '523075', name: 'Incapacidades - Administrativo', type: AccountType.EXPENSE, parent_code: '5230' },
  { code: '529900', name: 'Otros devengos - Administrativo', type: AccountType.EXPENSE, parent_code: '5299' },
  { code: '529910', name: 'Otros devengos - Administrativo', type: AccountType.EXPENSE, parent_code: '5299' },
  { code: '529920', name: 'Provisión Vacaciones - Administrativo', type: AccountType.EXPENSE, parent_code: '5299' },
  { code: '529930', name: 'Provisión Cesantías - Administrativo', type: AccountType.EXPENSE, parent_code: '5299' },
  { code: '529940', name: 'Provisión Prima - Administrativo', type: AccountType.EXPENSE, parent_code: '5299' },
  { code: '529950', name: 'Provisión Intereses Cesantías - Administrativo', type: AccountType.EXPENSE, parent_code: '5299' },
  { code: '4245', name: 'Recuperaciones y ajustes de inventario', type: AccountType.INCOME, parent_code: '42' },
  { code: '529595', name: 'Otros diversos', type: AccountType.EXPENSE, parent_code: '5295' },
  { code: '530535', name: 'Descuentos comerciales condicionados', type: AccountType.EXPENSE, parent_code: '5305' },
  // Ingresos financieros (4210)
  { code: '421005', name: 'Intereses', type: AccountType.INCOME, parent_code: '4210' },
  { code: '421010', name: 'Reajuste monetario', type: AccountType.INCOME, parent_code: '4210' },
  { code: '421015', name: 'Descuentos amortizados', type: AccountType.INCOME, parent_code: '4210' },
  { code: '421020', name: 'Diferencia en cambio', type: AccountType.INCOME, parent_code: '4210' },
  { code: '421025', name: 'Rendimientos financieros', type: AccountType.INCOME, parent_code: '4210' },
  { code: '421095', name: 'Otros ingresos financieros', type: AccountType.INCOME, parent_code: '4210' },
  // Gastos financieros (5305) - adicionales
  { code: '530506', name: 'Gastos bancarios', type: AccountType.EXPENSE, parent_code: '5305' },
  { code: '530515', name: 'Comisiones bancarias', type: AccountType.EXPENSE, parent_code: '5305' },
  { code: '530520', name: 'Intereses', type: AccountType.EXPENSE, parent_code: '5305' },
  { code: '530525', name: 'Diferencia en cambio', type: AccountType.EXPENSE, parent_code: '5305' },
  { code: '530540', name: 'Gastos manejo y emision de tarjetas', type: AccountType.EXPENSE, parent_code: '5305' },
  { code: '530545', name: 'GMF - Gravamen movimientos financieros', type: AccountType.EXPENSE, parent_code: '5305' },
  { code: '530555', name: 'Chequeras', type: AccountType.EXPENSE, parent_code: '5305' },
  { code: '530560', name: 'Multas sanciones y litigios', type: AccountType.EXPENSE, parent_code: '5305' },
  { code: '530595', name: 'Otros gastos financieros', type: AccountType.EXPENSE, parent_code: '5305' },
  { code: '613505', name: 'Comercio al por mayor y al por menor', type: AccountType.COST, parent_code: '6135' },
  // Nivel 8 (8 dígitos)
  { code: '11050501', name: 'Caja general', type: AccountType.ASSET, parent_code: '110505' },
  { code: '11100501', name: 'Moneda nacional', type: AccountType.ASSET, parent_code: '111005' },
  { code: '13050501', name: 'Clientes nacionales', type: AccountType.ASSET, parent_code: '130505' },
  { code: '13300501', name: 'Anticipo a Proveedores', type: AccountType.ASSET, parent_code: '133005' },
  { code: '13301505', name: 'Anticipos a Empleados', type: AccountType.ASSET, parent_code: '133015' },
  { code: '13551521', name: 'Retefuente Ventas', type: AccountType.ASSET, parent_code: '135515' },
  { code: '13551705', name: 'Reteiva Ventas', type: AccountType.ASSET, parent_code: '135517' },
  { code: '13551809', name: 'Reteica Ventas', type: AccountType.ASSET, parent_code: '135518' },
  { code: '22050501', name: 'Proveedores nacionales', type: AccountType.LIABILITY, parent_code: '220505' },
  { code: '23654001', name: 'Retefuente Compras', type: AccountType.LIABILITY, parent_code: '236540' },
  { code: '23654099', name: 'Retefuente por pagar', type: AccountType.LIABILITY, parent_code: '236540' },
  { code: '23670101', name: 'Reteiva Compras', type: AccountType.LIABILITY, parent_code: '236701' },
  { code: '23670105', name: 'Reteiva por pagar', type: AccountType.LIABILITY, parent_code: '236701' },
  { code: '23680509', name: 'Reteica Compras', type: AccountType.LIABILITY, parent_code: '236805' },
  { code: '23680599', name: 'Reteica por pagar', type: AccountType.LIABILITY, parent_code: '236805' },
  { code: '24080501', name: 'Iva generado en ventas', type: AccountType.LIABILITY, parent_code: '240805' },
  { code: '24081001', name: 'Iva descontable por compras', type: AccountType.LIABILITY, parent_code: '240810' },
  { code: '24950101', name: 'Impuesto al consumo en ventas', type: AccountType.LIABILITY, parent_code: '249501' },
  { code: '24950105', name: 'INC por pagar', type: AccountType.LIABILITY, parent_code: '249501' },
  { code: '24950201', name: 'Impuesto bolsas en ventas', type: AccountType.LIABILITY, parent_code: '249502' },
  { code: '24950202', name: 'Impuesto bolsas por pagar', type: AccountType.LIABILITY, parent_code: '249502' },
  { code: '28050501', name: 'Anticipo de Clientes', type: AccountType.LIABILITY, parent_code: '280505' },
  { code: '37050501', name: 'Utilidades o excedentes acumulados', type: AccountType.EQUITY, parent_code: '370505' },
  { code: '41350501', name: 'Comercio al por mayor de productos', type: AccountType.INCOME, parent_code: '413505' },
  { code: '41350502', name: 'Descuentos', type: AccountType.INCOME, parent_code: '413505' },
  { code: '41350503', name: 'Venta de bolsas plásticas', type: AccountType.INCOME, parent_code: '413505' },
  { code: '51550502', name: 'Viaticos', type: AccountType.EXPENSE, parent_code: '515505' },
  { code: '52959505', name: 'Gastos diversos', type: AccountType.EXPENSE, parent_code: '529595' },
  { code: '53053501', name: 'Descuentos comerciales condicionados', type: AccountType.EXPENSE, parent_code: '530535' },
  { code: '424520', name: 'Ganancias por sobrantes de inventarios', type: AccountType.INCOME, parent_code: '4245' },
  { code: '613595', name: 'Otros costos – mermas y ajustes de inventario', type: AccountType.COST, parent_code: '6135' },
  { code: '61350501', name: 'Comercio al por mayor y al por menor', type: AccountType.COST, parent_code: '613505' },
];

export async function seedPuc(prisma: PrismaClient) {
  console.log('📊 Seeding PUC (Plan Único de Cuentas)...');

  // Primero las clases raíz (sin padre)
  for (const cls of PUC_CLASSES) {
    await prisma.chartOfAccount.upsert({
      where: { code: cls.code },
      update: { name: cls.name, type: cls.type },
      create: {
        code: cls.code,
        name: cls.name,
        type: cls.type,
        parent_code: null,
        is_active: true,
      },
    });
  }

  // Luego las cuentas con padre (en orden jerárquico)
  for (const acc of PUC_ACCOUNTS) {
    await prisma.chartOfAccount.upsert({
      where: { code: acc.code },
      update: { name: acc.name, type: acc.type, parent_code: acc.parent_code },
      create: {
        code: acc.code,
        name: acc.name,
        type: acc.type,
        parent_code: acc.parent_code,
        is_active: true,
      },
    });
  }

  const total = PUC_CLASSES.length + PUC_ACCOUNTS.length;
  console.log(`   ✅ ${total} cuentas PUC creadas\n`);
}
