/**
 * Tipos de Obligaciones Tributarias - Colombia
 * Catálogo de obligaciones fiscales con periodicidad y aplicabilidad
 */
export const taxObligationTypes = [
  {
    id: '063eb13d-b58b-40e4-b41e-555d2e27ef9a',
    code: 'ACTIVOS_EXTERIOR',
    name: 'Activos en el Exterior',
    description: 'Declaración de activos en el exterior',
    category: 'nacional',
    periodicity: 'anual',
    nit_digit_type: 'last_1',
    applies_to_gran_contribuyente: true,
    applies_to_persona_juridica: true,
    applies_to_persona_natural: true,
    applies_to_rst: false,
    has_multiple_installments: false,
    installment_count: 1,
    display_order: 90,
  },
  {
    id: '1cffb63e-ca37-4893-a53c-25065aa0f9be',
    code: 'GASOLINA_ACPM',
    name: 'Gasolina y ACPM',
    description: 'Declaración mensual y pago de impuesto a gasolina y ACPM',
    category: 'nacional',
    periodicity: 'mensual',
    nit_digit_type: 'independent',
    applies_to_gran_contribuyente: true,
    applies_to_persona_juridica: true,
    applies_to_persona_natural: false,
    applies_to_rst: false,
    has_multiple_installments: false,
    installment_count: 1,
    display_order: 50,
  },
  {
    id: '2547fae6-3f97-4120-866d-3717c744dfe9',
    code: 'RETEFUENTE',
    name: 'Retención en la Fuente',
    description: 'Declaración mensual y pago de retención en la fuente',
    category: 'nacional',
    periodicity: 'mensual',
    nit_digit_type: 'last_1',
    applies_to_gran_contribuyente: true,
    applies_to_persona_juridica: true,
    applies_to_persona_natural: true,
    applies_to_rst: false,
    has_multiple_installments: false,
    installment_count: 1,
    display_order: 20,
  },
  {
    id: '2de9fa5d-a217-401a-bbbd-e1b1cc7094b3',
    code: 'PT_PAIS_POR_PAIS',
    name: 'Informe País por País',
    description: 'Informe país por país de precios de transferencia',
    category: 'nacional',
    periodicity: 'anual',
    nit_digit_type: 'independent',
    applies_to_gran_contribuyente: true,
    applies_to_persona_juridica: true,
    applies_to_persona_natural: false,
    applies_to_rst: false,
    has_multiple_installments: false,
    installment_count: 1,
    display_order: 72,
  },
  {
    id: '39099b6a-86d7-4b22-8f1b-cb02a2f17c14',
    code: 'RST_BIMESTRAL',
    name: 'RST Anticipo Bimestral',
    description: 'Anticipo bimestral del Régimen Simple',
    category: 'nacional',
    periodicity: 'bimestral',
    nit_digit_type: 'last_1',
    applies_to_gran_contribuyente: false,
    applies_to_persona_juridica: true,
    applies_to_persona_natural: true,
    applies_to_rst: true,
    has_multiple_installments: false,
    installment_count: 1,
    display_order: 31,
  },
  {
    id: '3c20d6f7-d991-459b-a5e7-cc154843c57c',
    code: 'PES_BIMESTRAL',
    name: 'PES Pagos Anticipados',
    description: 'Pagos anticipados bimestrales - Presencia Económica Significativa',
    category: 'nacional',
    periodicity: 'bimestral',
    nit_digit_type: 'independent',
    applies_to_gran_contribuyente: false,
    applies_to_persona_juridica: true,
    applies_to_persona_natural: false,
    applies_to_rst: false,
    has_multiple_installments: false,
    installment_count: 1,
    display_order: 110,
  },
  {
    id: '53b608c5-1089-44c2-a39e-96a0c35bdf8c',
    code: 'BEBIDAS_AZUCARADAS',
    name: 'Bebidas Ultraprocesadas',
    description: 'Impuesto a bebidas ultraprocesadas azucaradas y productos comestibles',
    category: 'nacional',
    periodicity: 'bimestral',
    nit_digit_type: 'independent',
    applies_to_gran_contribuyente: true,
    applies_to_persona_juridica: true,
    applies_to_persona_natural: false,
    applies_to_rst: false,
    has_multiple_installments: false,
    installment_count: 1,
    display_order: 81,
  },
  {
    id: '5e559dfd-a04f-4dd9-adfe-e5fe2613c582',
    code: 'PES_ANUAL',
    name: 'PES Declaración Anual',
    description: 'Declaración anual - Presencia Económica Significativa',
    category: 'nacional',
    periodicity: 'anual',
    nit_digit_type: 'independent',
    applies_to_gran_contribuyente: false,
    applies_to_persona_juridica: true,
    applies_to_persona_natural: false,
    applies_to_rst: false,
    has_multiple_installments: false,
    installment_count: 1,
    display_order: 111,
  },
  {
    id: '6a21b965-da68-4f0f-9146-7ce6bcb5d6f3',
    code: 'IVA_CUATRIMESTRAL',
    name: 'IVA Cuatrimestral',
    description: 'Declaración y pago cuatrimestral de IVA',
    category: 'nacional',
    periodicity: 'cuatrimestral',
    nit_digit_type: 'last_1',
    applies_to_gran_contribuyente: false,
    applies_to_persona_juridica: true,
    applies_to_persona_natural: true,
    applies_to_rst: false,
    has_multiple_installments: false,
    installment_count: 1,
    display_order: 11,
  },
  {
    id: '6dbd5f8e-0a03-4bac-afea-a9d07fe74334',
    code: 'RENTA_GC',
    name: 'Renta Grandes Contribuyentes',
    description: 'Declaración de renta para Grandes Contribuyentes',
    category: 'nacional',
    periodicity: 'anual',
    nit_digit_type: 'last_1',
    applies_to_gran_contribuyente: true,
    applies_to_persona_juridica: false,
    applies_to_persona_natural: false,
    applies_to_rst: false,
    has_multiple_installments: true,
    installment_count: 3,
    display_order: 1,
  },
  {
    id: '81f8cc35-7027-4395-b64e-06d1d704d515',
    code: 'RENTA_PJ',
    name: 'Renta Personas Jurídicas',
    description: 'Declaración de renta para Personas Jurídicas',
    category: 'nacional',
    periodicity: 'anual',
    nit_digit_type: 'last_1',
    applies_to_gran_contribuyente: false,
    applies_to_persona_juridica: true,
    applies_to_persona_natural: false,
    applies_to_rst: false,
    has_multiple_installments: true,
    installment_count: 2,
    display_order: 2,
  },
  {
    id: '8c59e30e-898a-437a-a404-a474f993ea9b',
    code: 'RST_ANUAL',
    name: 'RST Declaración Anual',
    description: 'Declaración anual del Régimen Simple de Tributación',
    category: 'nacional',
    periodicity: 'anual',
    nit_digit_type: 'last_2',
    applies_to_gran_contribuyente: false,
    applies_to_persona_juridica: true,
    applies_to_persona_natural: true,
    applies_to_rst: true,
    has_multiple_installments: false,
    installment_count: 1,
    display_order: 30,
  },
  {
    id: '987d6707-2b4d-42f4-affd-8f2cadf5b5cc',
    code: 'IVA_BIMESTRAL',
    name: 'IVA Bimestral',
    description: 'Declaración y pago bimestral de IVA',
    category: 'nacional',
    periodicity: 'bimestral',
    nit_digit_type: 'last_1',
    applies_to_gran_contribuyente: true,
    applies_to_persona_juridica: true,
    applies_to_persona_natural: true,
    applies_to_rst: false,
    has_multiple_installments: false,
    installment_count: 1,
    display_order: 10,
  },
  {
    id: '988e75a7-53e8-4268-af37-a2139f0ba88e',
    code: 'RUB',
    name: 'Registro Beneficiarios Finales',
    description: 'Actualización del Registro Único de Beneficiarios Finales',
    category: 'nacional',
    periodicity: 'trimestral',
    nit_digit_type: 'independent',
    applies_to_gran_contribuyente: true,
    applies_to_persona_juridica: true,
    applies_to_persona_natural: true,
    applies_to_rst: false,
    has_multiple_installments: false,
    installment_count: 1,
    display_order: 100,
  },
  {
    id: 'a510cfce-5883-4130-9dd6-cf848f783d6d',
    code: 'PATRIMONIO',
    name: 'Impuesto al Patrimonio',
    description: 'Declaración y pago del impuesto al patrimonio',
    category: 'nacional',
    periodicity: 'anual',
    nit_digit_type: 'last_1',
    applies_to_gran_contribuyente: true,
    applies_to_persona_juridica: true,
    applies_to_persona_natural: true,
    applies_to_rst: false,
    has_multiple_installments: true,
    installment_count: 2,
    display_order: 60,
  },
  {
    id: 'b1361431-117c-4f9c-a5cc-9695da8376cf',
    code: 'CARBONO',
    name: 'Impuesto al Carbono',
    description: 'Declaración y pago del impuesto al carbono',
    category: 'nacional',
    periodicity: 'bimestral',
    nit_digit_type: 'independent',
    applies_to_gran_contribuyente: true,
    applies_to_persona_juridica: true,
    applies_to_persona_natural: false,
    applies_to_rst: false,
    has_multiple_installments: false,
    installment_count: 1,
    display_order: 51,
  },
  {
    id: 'b3cfe6d6-7e22-48de-b0c9-2c6a4ce73eff',
    code: 'PT_INFORMATIVA',
    name: 'Precios Transferencia - Informativa',
    description: 'Declaración informativa de precios de transferencia',
    category: 'nacional',
    periodicity: 'anual',
    nit_digit_type: 'last_1',
    applies_to_gran_contribuyente: true,
    applies_to_persona_juridica: true,
    applies_to_persona_natural: false,
    applies_to_rst: false,
    has_multiple_installments: false,
    installment_count: 1,
    display_order: 70,
  },
  {
    id: 'ba5eb4b2-bf3b-4c8a-94b0-caa6c82f4e75',
    code: 'CONSUMO',
    name: 'Impuesto al Consumo',
    description: 'Declaración y pago bimestral del impuesto nacional al consumo',
    category: 'nacional',
    periodicity: 'bimestral',
    nit_digit_type: 'last_1',
    applies_to_gran_contribuyente: true,
    applies_to_persona_juridica: true,
    applies_to_persona_natural: true,
    applies_to_rst: false,
    has_multiple_installments: false,
    installment_count: 1,
    display_order: 40,
  },
  {
    id: 'c93a020a-2844-4550-a435-554d704502ba',
    code: 'PLASTICOS',
    name: 'Productos Plásticos Uso Único',
    description: 'Impuesto a productos plásticos de un solo uso',
    category: 'nacional',
    periodicity: 'anual',
    nit_digit_type: 'independent',
    applies_to_gran_contribuyente: true,
    applies_to_persona_juridica: true,
    applies_to_persona_natural: false,
    applies_to_rst: false,
    has_multiple_installments: false,
    installment_count: 1,
    display_order: 80,
  },
  {
    id: 'd1de6cd3-1327-4393-90de-5d01685fd648',
    code: 'IVA_EXTERIOR',
    name: 'IVA Prestadores Exterior',
    description: 'IVA para prestadores de servicios desde el exterior',
    category: 'nacional',
    periodicity: 'bimestral',
    nit_digit_type: 'independent',
    applies_to_gran_contribuyente: false,
    applies_to_persona_juridica: true,
    applies_to_persona_natural: false,
    applies_to_rst: false,
    has_multiple_installments: false,
    installment_count: 1,
    display_order: 12,
  },
  {
    id: 'e2543bb6-0f93-4792-a574-ca1857a000d9',
    code: 'RENTA_PN',
    name: 'Renta Personas Naturales',
    description: 'Declaración de renta para Personas Naturales',
    category: 'nacional',
    periodicity: 'anual',
    nit_digit_type: 'last_2',
    applies_to_gran_contribuyente: false,
    applies_to_persona_juridica: false,
    applies_to_persona_natural: true,
    applies_to_rst: false,
    has_multiple_installments: false,
    installment_count: 1,
    display_order: 3,
  },
  {
    id: 'eb4708e4-97ad-4c6d-b3a7-7209eee0fc43',
    code: 'PT_DOCUMENTACION',
    name: 'Precios Transferencia - Documentación',
    description: 'Documentación comprobatoria (informe local e informe maestro)',
    category: 'nacional',
    periodicity: 'anual',
    nit_digit_type: 'last_1',
    applies_to_gran_contribuyente: true,
    applies_to_persona_juridica: true,
    applies_to_persona_natural: false,
    applies_to_rst: false,
    has_multiple_installments: false,
    installment_count: 1,
    display_order: 71,
  },
  {
    id: 'f447d354-62b3-4ac9-89ec-c6c5c1ed5c52',
    code: 'RST_IVA_CONSOLIDADA',
    name: 'RST Consolidada IVA',
    description: 'Declaración consolidada de IVA para RST',
    category: 'nacional',
    periodicity: 'anual',
    nit_digit_type: 'last_2',
    applies_to_gran_contribuyente: false,
    applies_to_persona_juridica: true,
    applies_to_persona_natural: true,
    applies_to_rst: true,
    has_multiple_installments: false,
    installment_count: 1,
    display_order: 32,
  },
];
