/**
 * Reglas de Aportes por Subtipo de Trabajador - Colombia
 * Configuración de tasas y aplicabilidad de aportes según subtipo
 */
export const workerSubtypeRules = [
  {
    id: '01e1c75d-9cc3-460c-9f58-4b586bc5536e',
    sub_type_worker_id: '8',
    health_employee_rate: 0.00,
    health_employer_rate: 12.00,
    pension_employee_rate: null,
    pension_employer_rate: null,
    health_employee_pays: false,
    pension_employee_pays: false,
    ccf_applies: true,
    icbf_applies: true,
    sena_applies: true,
    arl_applies: true,
    fsp_applies: true,
    fsp_special_rate: 1.00,
    ibc_min_smmlv_percentage: null,
    legal_notes: 'Ley 1739/2014: Pensionado >25 SMMLV, 1% solidaridad adicional',
    ui_display_name: null,
    ui_impacts: null,
    ui_color: 'amber',
  },
  {
    id: '058f3b10-b898-4f26-8899-434fc3e5133e',
    sub_type_worker_id: '3',
    health_employee_rate: 0.00,
    health_employer_rate: 12.00,
    pension_employee_rate: null,
    pension_employer_rate: null,
    health_employee_pays: false,
    pension_employee_pays: false,
    ccf_applies: false,
    icbf_applies: false,
    sena_applies: false,
    arl_applies: true,
    fsp_applies: false,
    fsp_special_rate: null,
    ibc_min_smmlv_percentage: null,
    legal_notes: 'Independiente pensionado: 12% salud sin parafiscales, no pensión',
    ui_display_name: null,
    ui_impacts: null,
    ui_color: 'amber',
  },
  {
    id: '18a97e2a-caa1-43b6-ac92-1b37a04278d1',
    sub_type_worker_id: '4',
    health_employee_rate: null,
    health_employer_rate: null,
    pension_employee_rate: null,
    pension_employer_rate: null,
    health_employee_pays: true,
    pension_employee_pays: false,
    ccf_applies: true,
    icbf_applies: true,
    sena_applies: true,
    arl_applies: true,
    fsp_applies: false,
    fsp_special_rate: null,
    ibc_min_smmlv_percentage: null,
    legal_notes: 'Ley 797/2003: Mayor edad sin requisitos, salud normal, no pensión',
    ui_display_name: null,
    ui_impacts: null,
    ui_color: 'amber',
  },
  {
    id: '5a93d558-8040-47f6-9951-e043ed5b3220',
    sub_type_worker_id: '2',
    health_employee_rate: 0.00,
    health_employer_rate: 12.00,
    pension_employee_rate: null,
    pension_employer_rate: null,
    health_employee_pays: false,
    pension_employee_pays: false,
    ccf_applies: true,
    icbf_applies: true,
    sena_applies: true,
    arl_applies: true,
    fsp_applies: false,
    fsp_special_rate: null,
    ibc_min_smmlv_percentage: null,
    legal_notes: 'Decreto 1703/2002: Pensionado activo no paga salud (empleador 12%), no cotiza pensión ni FSP',
    ui_display_name: 'Pensionado por vejez dependiente',
    ui_impacts: ["❌ No paga salud (empleador asume 12%)", "❌ No cotiza a pensión", "❌ No aporta a FSP", "✅ Aplican parafiscales normales"],
    ui_color: 'amber',
  },
  {
    id: '85e6ce2e-6b86-4896-a3d6-fa852ed23c4a',
    sub_type_worker_id: '11',
    health_employee_rate: 12.50,
    health_employer_rate: null,
    pension_employee_rate: null,
    pension_employer_rate: null,
    health_employee_pays: true,
    pension_employee_pays: false,
    ccf_applies: false,
    icbf_applies: false,
    sena_applies: false,
    arl_applies: true,
    fsp_applies: false,
    fsp_special_rate: null,
    ibc_min_smmlv_percentage: 40.00,
    legal_notes: 'Decreto 1047/2014: Conductor sin pensión, solo salud 12.5%, IBC 40% mín',
    ui_display_name: null,
    ui_impacts: null,
    ui_color: 'amber',
  },
  {
    id: '87683e1e-4c5f-46ed-b7de-8d301209ea24',
    sub_type_worker_id: '5',
    health_employee_rate: null,
    health_employer_rate: null,
    pension_employee_rate: null,
    pension_employer_rate: null,
    health_employee_pays: true,
    pension_employee_pays: false,
    ccf_applies: true,
    icbf_applies: true,
    sena_applies: true,
    arl_applies: true,
    fsp_applies: false,
    fsp_special_rate: null,
    ibc_min_smmlv_percentage: null,
    legal_notes: 'Cumplió requisitos pero no pensionado: No cotiza pensión ni FSP',
    ui_display_name: null,
    ui_impacts: null,
    ui_color: 'amber',
  },
  {
    id: '8a517aa7-f7e6-4a7e-8130-841ddf9eebe6',
    sub_type_worker_id: '6',
    health_employee_rate: null,
    health_employer_rate: null,
    pension_employee_rate: null,
    pension_employer_rate: null,
    health_employee_pays: true,
    pension_employee_pays: false,
    ccf_applies: true,
    icbf_applies: true,
    sena_applies: true,
    arl_applies: true,
    fsp_applies: false,
    fsp_special_rate: null,
    ibc_min_smmlv_percentage: null,
    legal_notes: 'Indemnización sustitutiva recibida: No pensión ni FSP',
    ui_display_name: null,
    ui_impacts: null,
    ui_color: 'amber',
  },
  {
    id: '909c8459-7a94-4c99-ab3c-7fec1195cda6',
    sub_type_worker_id: '9',
    health_employee_rate: 12.50,
    health_employer_rate: null,
    pension_employee_rate: 16.00,
    pension_employer_rate: null,
    health_employee_pays: true,
    pension_employee_pays: true,
    ccf_applies: false,
    icbf_applies: false,
    sena_applies: false,
    arl_applies: false,
    fsp_applies: false,
    fsp_special_rate: null,
    ibc_min_smmlv_percentage: null,
    legal_notes: 'Afiliación voluntaria: 12.5% salud + 16% pensión, sin parafiscales',
    ui_display_name: null,
    ui_impacts: null,
    ui_color: 'amber',
  },
  {
    id: '929cc4ad-bbb3-4069-9a6b-500d952af9e7',
    sub_type_worker_id: '10',
    health_employee_rate: 12.50,
    health_employer_rate: null,
    pension_employee_rate: 16.00,
    pension_employer_rate: null,
    health_employee_pays: true,
    pension_employee_pays: true,
    ccf_applies: false,
    icbf_applies: false,
    sena_applies: false,
    arl_applies: true,
    fsp_applies: false,
    fsp_special_rate: null,
    ibc_min_smmlv_percentage: 40.00,
    legal_notes: 'Decreto 1047/2014: Conductor independiente, IBC mínimo 40% SMMLV',
    ui_display_name: null,
    ui_impacts: null,
    ui_color: 'amber',
  },
  {
    id: '959ae852-139e-424a-b6a3-07a9caaaef05',
    sub_type_worker_id: '7',
    health_employee_rate: null,
    health_employer_rate: null,
    pension_employee_rate: null,
    pension_employer_rate: null,
    health_employee_pays: true,
    pension_employee_pays: false,
    ccf_applies: true,
    icbf_applies: true,
    sena_applies: true,
    arl_applies: true,
    fsp_applies: false,
    fsp_special_rate: null,
    ibc_min_smmlv_percentage: null,
    legal_notes: 'Régimen exceptuado: entidades autorizadas para recibir aportes exclusivamente de sus propios trabajadores',
    ui_display_name: null,
    ui_impacts: null,
    ui_color: 'amber',
  },
];
