export const ACCOUNT_NATURE_MAP: Record<string, 'DEBIT' | 'CREDIT'> = {
  ASSET: 'DEBIT',
  LIABILITY: 'CREDIT',
  EQUITY: 'CREDIT',
  INCOME: 'CREDIT',
  EXPENSE: 'DEBIT',
  COST: 'DEBIT',
  PRODUCTION_COST: 'DEBIT',
  DEBTOR_ACCOUNTS: 'DEBIT',
  CREDITOR_ACCOUNTS: 'CREDIT',
};
